### PR TITLE
LPS-61319 Users in a User Group do not inherit role permissions

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-61319

Hi Jorge,

so this one was a hard one, took me days to reveal it. In the end the root cause were two different mistakes that completely (and cleanly) removed this functionality from codebase, including tests :D

I wasn't successful running UserBagFactoryTest on localhost, so hope to see result from CI.

/cc @drewbrokke 
/cc @pei-jung, and I'm sorry I told you to prepare that PR, I was wrong all the time

### CODE REVIEW

**Comment by drewbrokke** [comment]
Thanks for looking at this @topolik!  It was educational for @pei-jung and I to go through creating the other pull, even if it didn't get used.

**Comment by Preston-Crary** [comment]
@topolik looks good to me. Thanks for fixing it.

**Comment by JorgeFerrer** [comment]
Hey @topolik, Thanks for working on this. I'm on vacation and I don't want to delay this fix more. If Drew and Pei-Jung confirm your fix is ok, then you guys have my ok.

@drewbrokke @pei-jung can one of you double check Tomas' solution?

**Comment by drewbrokke** [comment]
@JorgeFerrer @topolik  Looks good to me.

**Comment by pei-jung** [comment]
Looks good to me too. Thanks for working on this @topolik!

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/42214. Thanks for looking into this!

**Pull request closed without merging**
