### PR TITLE
[TECHNICAL SUPPORT] LPS-66160 Fix User Admin 'sites' section to be able to work with no selected user

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-66160

----
Author: @NorbertKocsis
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Thanks for the pull.

I will take care of it, but I need to wait a little bit since only critical
things are accepted right now in master (until the release).

**Comment by lipusz** [comment]
Got it! Thank you for the prompt reply, Jorge!

On Mon, Jun 6, 2016 at 7:16 PM, Jorge Ferrer <notifications@github.com>
wrote:

> Thanks for the pull.
>
> I will take care of it, but I need to wait a little bit since only critical
> things are accepted right now in master (until the release).
> El 6 jun. 2016 4:03 p. m., "Liferay Continuous Integration" <
> notifications@github.com> escribió:
>
> > Some tests FAILED!
> >
> > Build Time: 1 hour 15 minutes 39 seconds
> > Base Branch:
> >
> > Branch Name: master
> > <https://github.com/liferay/liferay-portal/tree/master>
> > Branch GIT ID: e195b726cddfe031f1033e8680b98a209ec5c980
> > <
> https://github.com/liferay/liferay-portal/commit/e195b726cddfe031f1033e8680b98a209ec5c980
> >
> > Job Summary:
> >
> > - *test-portal-acceptance-pullrequest(master)
> > <
> https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/177/
> >*
> > - test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk7
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9639/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-jboss64-mysql56-jdk8/0
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9640/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-hypersonic20-jdk7/0
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9641/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/0
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9642/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/1
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9643/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/2
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9644/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/0
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9645/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/1
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9646/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/10
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8034/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/11
> > <
> https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9631/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/12
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9649/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/13
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9650/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/14
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9651/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/15
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9652/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/16
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9653/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/17
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9654/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/18
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9655/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/19
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9656/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/2
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9647/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/20
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9657/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/21
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9658/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/22
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9659/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/23
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9660/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/24
> > <
> https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10773/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/25
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9661/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/26
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9662/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/27
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9663/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/28
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9664/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/29
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9665/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/3
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9648/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/30
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9667/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/31
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9666/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/32
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9668/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/33
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8035/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/34
> > <
> https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9899/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/35
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9248/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/36
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9249/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/37
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9250/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/38
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9251/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/39
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9252/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/4
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8028/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/40
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9253/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/41
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9255/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/42
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9254/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/43
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9256/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/44
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9927/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/45
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9928/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/5
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8029/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/6
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8030/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/7
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8031/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/8
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8032/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/9
> > <
> https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8033/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/0
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9930/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/1
> > <
> https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10419/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/2
> > <
> https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10420/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/0
> > <
> https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10605/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/1
> > <
> https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10606/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/2
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9466/
> >
> > -
> *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/0
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9468/
> >*
> > -
> *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/1
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9931/
> >*
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/2
> > <
> https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10421/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-weblogic121-mysql56-jdk8/0
> > <
> https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9632/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-wildfly10-mariadb100-jdk8/0
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9257/
> >
> > -
> > test-portal-acceptance-pullrequest-batch(master)/integration-db2105-jdk7
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9470/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic20-jdk7
> > <
> https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10679/
> >
> > -
> > test-portal-acceptance-pullrequest-batch(master)/integration-mysql56-jdk7
> > <
> https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10775/
> >
> > -
> *test-portal-acceptance-pullrequest-batch(master)/integration-oracle12-jdk7
> > <
> https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9566/
> >*
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/integration-postgresql94-jdk7
> > <
> https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9900/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/integration-sybase160-jdk7
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10183/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/lpkg-startup-jdk7
> > <
> https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9213/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-db2105-jdk7
> > <
> https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10777/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic20-jdk7
> > <
> https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9214/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql56-jdk7
> > <
> https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9260/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-oracle12-jdk7
> > <
> https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10680/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql94-jdk7
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9475/
> >
> > -
> >
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-sybase160-jdk7
> > <
> https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9901/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk7
> > <
> https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9567/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/plugins-compile-jdk7
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10184/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/portal-web-jdk7
> > <
> https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10059/
> >
> > -
> > test-portal-acceptance-pullrequest-batch(master)/ruby-sass-compiler-jdk7
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9669/
> >
> > -
> > test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk7
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10185/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk7
> > <
> https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10060/
> >
> > - test-portal-acceptance-pullrequest-batch(master)/tck-jdk7
> > <
> https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9670/
> >
> > - *test-portal-acceptance-pullrequest-batch(master)/unit-jdk7
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10186/
> >*
> > - test-portal-acceptance-pullrequest-source(master)
> > <
> https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/180/
> >
> >
> > For more details click here
> > <
> https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/177/jenkins-report.html
> >
> > .
> > ------------------------------
> > Failed Jobs:
> >
> > 1. test-portal-acceptance-pullrequest(master)
> > <
> https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/177/>
> Job
> > Results:
> >
> > 81 Jobs Passed.
> > 5 Jobs Failed.
> >
> > Completed with the status of FAILURE.
> >
> > 2.
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/0
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9468/>
> Job
> > Results:
> >
> > 1 Test Passed.
> > 1 Test Failed.
> > 1. PoshiRunner.test[623Upgrade#View623DataArchive]
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/9468//testReport/com.liferay.poshi.runner/PoshiRunner/test_623Upgrade_View623DataArchive_
> >
> > - 623Upgrade#View623DataArchive
> > <
> https://testray.liferay.com/reports/production//logs/test-1-11/1465217267056/test-portal-acceptance-pullrequest%28master%29/177/functional-tomcat8-sybase16-jdk8/0/0/623Upgrade_View623DataArchive/index.html.gz
> >
> > - Poshi Summary
> > <
> https://testray.liferay.com/reports/production//logs/test-1-11/1465217267056/test-portal-acceptance-pullrequest(master)/177/functional-tomcat8-sybase16-jdk8/0/0/
> >
> > - Console Output
> > <
> https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/9468//console
> >
> > 3.
> >
> test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/1
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9931/>
> Job
> > Results:
> >
> > 1 Test Passed.
> > 1 Test Failed.
> > 1. PoshiRunner.test[612Upgrade#View612DataArchive]
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/9931//testReport/com.liferay.poshi.runner/PoshiRunner/test_612Upgrade_View612DataArchive_
> >
> > - 612Upgrade#View612DataArchive
> > <
> https://testray.liferay.com/reports/production//logs/test-1-11/1465217267056/test-portal-acceptance-pullrequest%28master%29/177/functional-tomcat8-sybase16-jdk8/1/0/612Upgrade_View612DataArchive/index.html.gz
> >
> > - Poshi Summary
> > <
> https://testray.liferay.com/reports/production//logs/test-1-11/1465217267056/test-portal-acceptance-pullrequest(master)/177/functional-tomcat8-sybase16-jdk8/1/0/
> >
> > - Console Output
> > <
> https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/9931//console
> >
> > 4.
> >
> test-portal-acceptance-pullrequest-batch(master)/integration-oracle12-jdk7
> > <
> https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9566/>
> Job
> > Results:
> >
> > 5798 Tests Passed.
> > 1 Test Failed.
> > 1. JAASTest.testProcessLoginEvents
> > <
> https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=3,label_exp=!master/9566//testReport/com.liferay.portal.security.auth/JAASTest/testProcessLoginEvents
> >
> > 5. test-portal-acceptance-pullrequest-batch(master)/unit-jdk7
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10186/>
> Job
> > Results:
> >
> > 2313 Tests Passed.
> > 1 Test Failed.
> > 1. InitUtilTest.testBaseSeleniumTestCaseSpringConfigs
> > <
> https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/10186//testReport/com.liferay.portal.util/InitUtilTest/testBaseSeleniumTestCaseSpringConfigs
> >
> >
> > For upstream results, click here
> > <http://test-1-1/job/test-portal-acceptance-upstream(master)/>.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/JorgeFerrer/liferay-portal/pull/750#issuecomment-223968425
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AA0-wHSl8Hb5-K6zJ_7hMbZvhaJa6QHPks5qJCjOgaJpZM4IqWjQ
> >
>
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/750#issuecomment-224024815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfA4gxWovHkzt9viT-HMiUWWE3NafG4ks5qJFXbgaJpZM4IqWjQ>
> .
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Jorge,

Is it good for now to proceed with this pull?

@JorgeFerrer

**Comment by JorgeFerrer** [comment]
I prefer to wait a couple more days since there might still be another sync from master. All team leads are doing the same.

**Comment by lipusz** [comment]
Hi Jorge,

Is it good for now to proceed with this pull?

@JorgeFerrer

**Comment by JorgeFerrer** [comment]
Yes, I plan to send it tomorrow.

**Comment by lipusz** [comment]
Hi Jorge,

Sorry for the spam, I didn't want to re-send the same message what I had sent you 2 days ago. GitHub and Firefox don't like each other: every time I open a pull the comment box is filled out with my previous message, so when I closed the pull (to reopen and re-test) 3 hours ago, I also commented accidentally.

**Comment by JorgeFerrer** [comment]
Got it, no worries.

BTW, did you know that you can flag a restes by posting a message that says
ci:retest?

On Thu, Jun 16, 2016 at 12:48 PM, Tibor Lipusz <notifications@github.com>
wrote:

> Hi Jorge,
>
> Sorry for the spam, I didn't want to re-send the same message what I had
> sent you 2 days ago. GitHub and Firefox don't like each other: every time I
> open a pull the comment box is filled out with my previous message, so when
> I closed the pull (to reopen and re-test) 3 hours ago, I also commented
> accidentally.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/750#issuecomment-226451775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA0-wBiIWe5R2mbDdlT5CWuUOd-sbsyHks5qMSobgaJpZM4IqWjQ>
> .
>



-- 
Jorge Ferrer
Vice President, Engineering
@jorgeferrer <https://twitter.com/jorgeferrer>

*Liferay Inc*
Web <http://www.liferay.com> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>


*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by lipusz** [comment]
Yes, I did. But sometimes, especially when there are days spent since the
pull was opened, I close and reopen so GH can re-calculate the total diff
correctly. Otherwise, even after force push the diff and commit views are
not refreshed.

On Thu, Jun 16, 2016 at 1:13 PM, Jorge Ferrer <notifications@github.com>
wrote:

> Got it, no worries.
>
> BTW, did you know that you can flag a restes by posting a message that says
> ci:retest?
>
> On Thu, Jun 16, 2016 at 12:48 PM, Tibor Lipusz <notifications@github.com>
> wrote:
>
> > Hi Jorge,
> >
> > Sorry for the spam, I didn't want to re-send the same message what I had
> > sent you 2 days ago. GitHub and Firefox don't like each other: every
> time I
> > open a pull the comment box is filled out with my previous message, so
> when
> > I closed the pull (to reopen and re-test) 3 hours ago, I also commented
> > accidentally.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/JorgeFerrer/liferay-portal/pull/750#issuecomment-226451775
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AA0-wBiIWe5R2mbDdlT5CWuUOd-sbsyHks5qMSobgaJpZM4IqWjQ
> >
> > .
> >
>
>
>
> --
> Jorge Ferrer
> Vice President, Engineering
> @jorgeferrer <https://twitter.com/jorgeferrer>
>
> *Liferay Inc*
> Web <http://www.liferay.com> | Facebook <http://facebook.com/liferay> |
> Twitter <http://twitter.com/liferay>
>
>
> *Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
> los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
> exclusivo del destinatario (s) previsto y puede contener información
> confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
> uso, copia, divulgación o distribución. Si usted no es el destinatario, por
> favor póngase en contacto con el remitente por correo electrónico de
> respuesta y destruir todas las copias del mensaje original. Gracias.
>
> *Confidentiality Notice: *This e-mail message, including any attachments,
> sent on behalf of Liferay SL is for the sole use of the intended
> recipient(s) and may contain confidential and privileged information. Any
> unauthorized review, use, copying, disclosure or distribution is
> prohibited. If you are not the intended recipient, please contact the
> sender by reply e-mail and destroy all copies of the original message.
> Thank
> you.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/750#issuecomment-226456323>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfA4hrc1X_rhsi7MiixmxtnCkMlS2ynks5qMS_PgaJpZM4IqWjQ>
> .
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/pei-jung/liferay-portal/pull/117. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
