### PR TITLE
LPS-54116

### PR DESCRIPTION
**Pull request by hudakl**
Hi Jorge,

I'm currently working on the LPS-54116 and I come up with a solution which is implemented in this pull request. Unfortunately I came across a few contradictions between the operation on 6.2.x and master and after discussing those with Zsigmond, we considered that we should ask your advise regarding this topic.

As of 6.2 to if a user needs to access a portlet in the Control Panel, they need to have View permission for portlet itself and either "Sites > Site: Go to Site Administration" or "Portal: Go to Control Panel" permission depending on from where the portlet in question is available.
With the following LPS it was introduced to add the necessary permissions to the Roles automatically:
https://issues.liferay.com/browse/LPS-37729
The current issue is, that upon upgrade these permissions are not added to the Roles, so the users can't have access the administrative portlets which they should handle.

However, the capabilities of the function were limited with this ticket:
https://issues.liferay.com/browse/LPS-41410
...which added the highlighted check to decide if additional permissions needs to be added to the Role in question.
EditRolePermissionsAction.updateActions:
		if (selected &&
			-> (scope == ResourceConstants.SCOPE_COMPANY) &&
			actionId.equals(ActionKeys.ACCESS_IN_CONTROL_PANEL)) {

As far as I understand based on the description of LPS-41410 the intended operation is that in case the Role in question is a Site Role, the "Portal: Go to Control Panel" shouldn't be added, but with the logic above, the Site Roles will never get the necessary "Sites > Site: Go to Site Administration" permission.
The way I see these are sorted later in the code:
EditRolePermissionsAction.updateViewControlPanelPermission:
		if (ArrayUtil.contains(PortletCategoryKeys.ALL, controlPanelCategory)) {
			selResource = PortletKeys.PORTAL;
			actionId = ActionKeys.VIEW_CONTROL_PANEL;
		}
		else if (ArrayUtil.contains(
					PortletCategoryKeys.SITE_ADMINISTRATION_ALL,
					controlPanelCategory)) {

			selResource = Group.class.getName();
			actionId = ActionKeys.VIEW_SITE_ADMINISTRATION;
		}
For this reason I believe the changes of the LPS-41410 are unnecessary and for the verifying roles I used the logic on 6.2.x. Furthermore, as the portlet category is not yet available at the point where the VerifyProcess runs, I made the verify accessible from the Server Administration page.

Considering these do you think this approach could be an appropriate solution and can be provided to a customer in a SDH hotfix?
If you disagree, could you please describe how should this be working?

Thank you,
Laci

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey,

Thanks for your detailed explanation. I am in fact working with Drew to review this behavior in detail to determine how things should be working in all the scenarios you describe.

What I'm surprised about is the need for an upgrade though. Before 6.2 it was already necessary to have the ACCESS_IN_CONTROL_PANEL permission and all we have done is rename it in the UI to "Go to Site Administration" when appropriate and add it automatically when we determine it's desired. 

But a user who previously had access to a portlet in Control Panel should still have access to it even if it's now showed in Site Administration. What am I missing?

**Comment by hudakl** [comment]
Hi,

During my tests I experienced, that on 6.0 it was enough to have 'Access in Control Panel' permission to access the individual administrative portlets (like Web Content) and this was renamed to 'Access in Site Administration'. However, to access the Web Content portlet on 6.2 the 'Sites > Site: Go to Site Administration' and the 'Web Content > Web Content: View' permissions are also required.
I assume, that's why the automatic Permission assignment was introduced in the LPS-37729 and why the upgrade would be necessary.

Please let me know if you have further questions.

Thanks,
Laci

**Comment by JorgeFerrer** [comment]
Hey @hudakl,

I've just submitted the definitive fix for LPS-41410. Please take a look at
https://github.com/brianchandotcom/liferay-portal/pull/24748

I don't remember 6.0, but in 6.1 it was definitely still necessary to have the VIEW_CONTROL_PANEL permission to access any of the portlets in the Control Panel. In 6.2 we have split the Control Panel into the new Control Panel and Site Administration in the UI (under the hood it's still all the same). Because of that the permission VIEW_CONTROL_PANEL is sometimes displayed as "Go to Control Panel" and sometimes as "Go to Site Administration" depending on the context. But I don't think the permissions needed have changed.

We may have missed some case though. Do you have an specific example of data that allows a user to access a portlet like Web content in Control Panel in 6.1 but it does not allow accessing it in 6.2? If so, please send it to me and I'll use it to test your fix.

**Comment by hudakl** [comment]
Hi Jorge,

I performed additional tests to determine the minimum permissions required to set on the UI to access the portlets. I tested it on 6.0, 6.1 and 6.2 for Web Content and Users. I've got the following results:

Minimal permissions for accessing Web Content:
6.0.12:
Web Content: Access in Control Panel 

6.1.20:
Web Content: Access in Control Panel 
Web Content: View 

6.2.10:
Web Content > Web Content: View
Web Content: Access in Site Administration
Sites > Site: Go to Site Administration


Minimal permissions for accessing User:
6.0.12:
Users: Access in Control Panel 

6.1.20:
Users and Organizations: Access in Control Panel

6.2.10:
Portal: Go to Control Panel
Users and Organizations: Access in Control Panel

Please let me know if this answers your question.

Thank you,
Laci

**Comment by JorgeFerrer** [comment]
Ok, that's surprising (at least I did not remember it that way). It would mean that the "Go to control panel" permission did not exist in Liferay 6.1 and every user could access it. Can you confirm that?

**Comment by JorgeFerrer** [comment]
I just did some research and it was added in 6.0 and apparently even backported. See https://issues.liferay.com/browse/LPS-17039

**Comment by JorgeFerrer** [comment]
I was looking a little bit more at this and I need to correct one thing I've said: "Go to Site Administration" is not backed by the same action as "Go to Control Panel". The former is backed  by VIEW_SITE_ADMINISTRATION. Before this was introduced (for 6.2) the existing code was:
´´´
		if (layout.isTypeControlPanel()) {
			if (!permissionChecker.isSignedIn()) {
				return false;
			}

			if (PortalPermissionUtil.contains(
					permissionChecker, ActionKeys.VIEW_CONTROL_PANEL)) {

				return true;
			}

			if (Validator.isNotNull(controlPanelCategory)) {
				return true;
			}

			return false;
		}
´´´

Which means that the VIEW_CONTROL_PANEL permission was already required. This does not match with your findings which is puzzling me. I'd appreciate any insight from your side.

**Comment by JorgeFerrer** [comment]
For the record, I've just found that the original code added in LPS-17039 was:

```	
	if (group.isControlPanel()) {
			if (PortalPermissionUtil.contains(
					permissionChecker, ActionKeys.VIEW_CONTROL_PANEL)) {

				return true;
			}
			else {
				if (controlPanelCategory != null) {
					return true;
				}
				else {
					return false;
				}
			}
		}
´´´

That means that the user cannot access the frontpage but he would be able to access an specific category.

**Comment by hudakl** [comment]
Hi,

I could find the 'Portal: Go to Control Panel' permission on 6.1, but it doesn't appear to be present in 6.0. 
On 6.1 I performed a few additional tests and I found that with the 'Portal: Go to Control Panel' although the user could go to the control panel, but to gain access to the other portlets as well one would need the 'Access in Control Panel' permission for the individual portlets as well. 

However on 6.2. the 'Sites > Site: Go to Site Administration' is also seems to be necessary to access the portlet. 
Here is the corresponding part of the code in ServicePreAction.initThemeDisplay:
	if (signedIn &&
			PortalPermissionUtil.contains(
				permissionChecker, ActionKeys.VIEW_CONTROL_PANEL)) {

			showControlPanelIcon = true;
		}

		themeDisplay.setShowControlPanelIcon(showControlPanelIcon);
		...
		boolean showSiteAdministrationIcon = false;

		if (signedIn &&
			GroupPermissionUtil.contains(
				permissionChecker, group,
				ActionKeys.VIEW_SITE_ADMINISTRATION)) {

			showSiteAdministrationIcon = true;
		}

		themeDisplay.setShowSiteAdministrationIcon(showSiteAdministrationIcon);

Thanks,
Laci

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Closing for the time being. As agreed, the way to do this would need to start with moving logic from the Actions to the service implementations.

**Pull request closed without merging**
