### PR TITLE
LPS-62523 remove default language from web content, ddm structures and ddl

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @marcellustavares, 

we are removing the possibility to change the default language of web content because that feature produces many issues and now the we have a site default language it is a bit redundant. Our PM suggested that the same applies to Structures and DDL, therefore we have applied the change everywhere.

(The feature can still be enabled in System Settings but it should be gone in the next major release)

Could you please have a look? thank you!

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Julio,

The only reason why the new field that you have added is looking so bad is because you have not propagated the changes from Language.properties to Language_en.properties and there is a bug that causes the fallback to Language.properties not work for modules (I reported it several weeks ago)

**Pull request closed without merging**
