### PR TITLE
LPS-48156 Apply inner exceptions pattern to PrincipalException

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Jorge, 

I left the one in `MarketplacePermission` untouched because it was causing build failure. I've talked to Joan from the Marketplace team, and she has no idea why changing the exception will cause error in the plugin. So I reverted the change for now.

/cc @natecavanaugh

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27211. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/9683bd1~5...9683bd1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
