### PR TITLE
LPS-65497

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65497](https://issues.liferay.com/browse/LPS-65497).<br><br>/cc @NorbertKocsis @lipusz @pei-jung @Preston-Crary

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Drew,

This is pretty surprising. Did you find out if this method was always like that or that line was removed at some later point? If the latter, was it accidental or on purpose for some reason?

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39541. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Hey @JorgeFerrer, this line was taken out at some point, but I haven't yet found the commit.  When I find it I'll add it here.

**Comment by Preston-Crary** [comment]
Sorry guys: https://github.com/liferay/liferay-portal/commit/6ed051a#diff-2b0cae0e7f9914274883423c68678ea1L4795

**Comment by drewbrokke** [comment]
Thanks @Preston-Crary :)

**Pull request closed without merging**
