### PR TITLE
LPS-60595 Navigating to a configuration factory in System Settings throws a NullPointerException

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-60595](https://issues.liferay.com/browse/LPS-60595).<br><br>/cc @pei-jung @alee8888

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32354. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Thanks for catching this Drew!

I'm refactoring the portlet to avoid reusing views so much which I hope will prevent issues like this.

**Comment by drewbrokke** [comment]
You're welcome :) There are a couple other issues with the portlet (pagination and category persistence, in particular), so I'm glad you're taking a look at it.  Let me know if I can help.

**Comment by JorgeFerrer** [comment]
Hey Drew,

Ok, thanks for letting me know about those two other issues. Since I'm making changes right now I will take care of them.

**Pull request closed without merging**
