### PR TITLE
Joshuacords j cords lps 73348 2

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

Hi Jorge,

I am sending you this pull request because Jonathan Mccann is out of the office for the week. Let me or Josh know if you have any questions regarding this pull.

Thanks,
Sam

Notes from Josh:

> https://issues.liferay.com/browse/LPP-25804
> https://issues.liferay.com/browse/LPS-73348
> 
> Because Resource Block Permissions function differently than Resource Permissions in that their group scope data is lossy, this PR is providing improved warnings to the User before their change overwrites Permissions set in the Group Scope. (Changing the functionality is too big of a task, as discussed here: https://issues.liferay.com/browse/LPP-25978)
> 
> Additionally, this PR removes an issue where setting a permission for a ResourceBlock resource at the company level will no longer overwrite all permissions on that resource, instead, it will only overwrite the permission changed.
> 
> Note: Not all language keys have been generated.

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @rotty3000, 

I'm not very familiar with ResourceBlocks and as far as I remember you were the one who wrote that implementation of the permissions system. If that's the case, could you take a look at this to verify that it's correct? If not, who do you think could review this?

In addition to that, if this code is correct, do you think it would be possible to encapsulate the specificities of ResourceBlocks in an inner class so that it doesn't affect the frontend code?

**Comment by AngeloJ** [comment]
@JorgeFerrer, Ray is on vacation until the 17th. Is there anyone else we can run the pull by?

**Comment by JorgeFerrer** [comment]
@AngeloJ The only person I can think of is Preston, who is now in Shuyang's team might have worked with Resource Blocks before.

**Comment by AngeloJ** [comment]
Thanks @JorgeFerrer , I'll contact him and see if he can take a look.

**Comment by Preston-Crary** [comment]
@joshuacords resend it to me with the changes we talked about this morning. Thanks!

**Comment by Preston-Crary** [comment]
ci:close

**Comment by joshuacords** [comment]
Reopened here: https://github.com/Preston-Crary/liferay-portal/pull/347

**Pull request closed without merging**
