### PR TITLE
LPS-75377 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-75377

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:open

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55601. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/c0949e7153fe~4...c0949e7153fe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
