### PR TITLE
LPS-67890 Exported multi-value settings appear in separate lines

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @JorgeFerrer,

With the changes, multi-value settings are now exported in one line:

`key=["value1","value2","value3"]`

See sample output for [com.liferay.iframe.web.configuration.IFramePortletInstanceConfiguration.config](https://gist.github.com/pei-jung/30a5ecf66fcff4fef0ea0b4a79c16a29)

/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Sorry Pei-Jung, I didn't see this pull. I started today but didn't have time to finish and won't be able for the rest of the week. Since I'm not an expert in tests either, if Drew has already reviewed the test go ahead and send it to Brian.

**Comment by pei-jung** [comment]
Sure thing. I'll send the pr to Drew for review. Thanks @JorgeFerrer.

**Comment by pei-jung** [comment]
https://github.com/drewbrokke/liferay-portal/pull/236

**Pull request closed without merging**
