### PR TITLE
LPS-64914 Restructure jsps in Contacts Center Web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Drew, Pei-Jung,

I was looking into this and it looks good but there are still quite a few JSPs remaining at the root level, including one named view.jsp, why is that?

**Comment by drewbrokke** [comment]
I decided to leave that one view.jsp at the root level because it was referenced by several other view.jsps.  I left configuration.jsp at the root level also because it is shared by all the portlets.

I think we can move all the other view*.jsps into the contacts_center dir.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38801. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
