### PR TITLE
LPS-68443 After exporting configurations, you must refresh to use the ellipsis menus in System Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-68443](https://issues.liferay.com/browse/LPS-68443).<br><br>This is a really quick fix (same as I did for [LPS-66650](https://issues.liferay.com/browse/LPS-66650))<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43575. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke, good job on this. For this type of changes I trust you guys to send it directly to Brian. Don't want to slow you down.

**Pull request closed without merging**
