### PR TITLE
LPS-119152 As an application developer I can filter the implementation of InfoItemObjectProvider I obtain from InfoItemServiceTracker to ensure they support a specific InfoItemIdentifier

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@jkappler This pull includes a working implementation of the proposal to support specifying the type of InfoItemIdentifier which must be supported by InfoItemObjectProvider. \n\n However, since it is fully backwards compatible I think it would be better to table it for now and get back to it after 7.3 is released. After all, the biggest value of this will come for 7.4 if we leverage InfoItemIdentifier and InfoItemReference to support a more flexible way to reference items with each other.

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
For the record, the work done in this pull is documented here: https://docs.google.com/document/d/1KjWCW26JqbyXlS-h3tjsdN621eNb9_i-7fjOStKeqSM/edit?ts=5f33cca7

**Comment by csierra** [comment]
hey @JorgeFerrer, 

I see you did not change the service tracker customizer to use one on the existing as we discussed. Do you want me to send a followup?

Carlos.

**Comment by JorgeFerrer** [comment]
You are right, I focused on the InfoItemServiceFilter and forgot about that part. It would be great if you could send a follow up, but let's do it after 7.3 is out. Now that it's clear that this can be added later in a backwards compatible way there is no pressure to finish it for this release.
Thanks!

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @csierra ,
I'm getting back to this to push it to master for 7.4.
I've already rebased the code to master and resolved the conflicts.

Regarding the changes you suggested to "service tracker customizer", I'm afraid I don't remember them and I can't find where we had that conversation. If you do, would you mind explaining them again?
If you want to send code, it would be most welcome as well :)

/cc @jkappler

**Comment by csierra** [comment]
hey @JorgeFerrer... please see https://github.com/JorgeFerrer/liferay-portal/pull/898

**Pull request closed without merging**
