### PR TITLE
LPS-60091

### PR DESCRIPTION
**Pull request by arbetts**
i found these changes lost in pull request limbo. The fix has already been committed but i think we should add the verify process, since otherwise clients will still have the problem after upgrading.

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @arbetts @Preston-Crary,

Thanks for the contribution, however we cannot do it that way. There are Liferay installations with millions of users. If, for example, 100,000 of them are inactive, that code would load all of them at once into memory and then update each of them. That would be really bad from a performance and scalability perspective.

In fact, in this specific case I think it should be possible to write a single SQL query that sets the group to inactive when it belongs to a user that is inactive. Can you try that?

**Comment by arbetts** [comment]
@JorgeFerrer 

@Preston-Crary is writing the sql query to do the bulk update

**Comment by Preston-Crary** [comment]
See https://github.com/JorgeFerrer/liferay-portal/pull/685

**Pull request closed without merging**
