### PR TITLE
LPS-60805

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Jorge,

Sending this to you as you helped out with LPS-60932 as well and I don't know who else is even remotely familiar with this code :)

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
I'm not a big expert in ISBN validation or even in this portlet. I was just involved recently since it was used by Ray as an example to use OSGi configuration.

In any case I've taken a look and I don't see anything wrong with the changes. If you've tested it through I think it should be fine to send to Brian.

**Comment by bejondshao** [comment]
Hey @hhuijser ,

Would you redirect this?

Thanks

**Pull request closed without merging**
