### PR TITLE
LPS-53409 Input validator does not allow special characters in user screen names

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-53409

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung,

Can yo please take a look at the failing tests? They seem to be related.

**Comment by pei-jung** [comment]
Yeah, I need to update the integration tests for screen names. I will do that and resend.

**Comment by pei-jung** [comment]
Updated tests and resent as https://github.com/JorgeFerrer/liferay-portal/pull/512.

**Pull request closed without merging**
