### PR TITLE
LPS-53147

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @jonathanmccann,

The fix seems correct to me. However I'm surprised this was not taking into account. 
@epgarcia was it you who worked with me on this some time ago? If so, can you take a look at the issue and the fix as well?

**Comment by epgarcia** [comment]
Hi @JorgeFerrer,

I don't remember this particular case but the fix also seems correct to me. I think it was @jcampoy who worked on this (see LPS-43074). @jcampoy could you take a look?

Thanks!

**Comment by jcampoy** [comment]
Hi @epgarcia ,

I will take a look next Monday.

Regards

//cc @JorgeFerrer , @jonathanmccann

**Comment by jcampoy** [comment]
We need to skip customization for company-wide portlets, see https://github.com/JorgeFerrer/liferay-portal/pull/457

**Pull request closed without merging**
