### PR TITLE
LPS-54956

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-54956](https://issues.liferay.com/browse/LPS-54956).<br><br>@pei-jung, @natecavanaugh

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey Drew, there seems to be a compilation error in the contacts-portlet after this change. Can you look into it?

**Comment by drewbrokke** [comment]
Updated with a plugins pull request to Brian: https://github.com/brianchandotcom/liferay-plugins/pull/4509

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke, can you fix the remaining issues?

**Comment by drewbrokke** [comment]
Yes,  I actually have a fix ready, I just mistakenly submitted the
plugins pull to Brian. I'll submit it to you shortly.

On Monday, April 27, 2015, Jorge Ferrer <notifications@github.com> wrote:

> Hey @drewbrokke <https://github.com/drewbrokke>, can you fix the
> remaining issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/518#issuecomment-96694720>
> .
>


-- 
--
Drew Brokke

Jr. Software Engineer, Liferay, Inc.

*Liferay Symposium North America*
November 16-17, 2015 | Chicago, IL
CFP is now open! | www.liferay.com/northamerica2015

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke,

I'm sorry that it took so long to review this. Overall it looks very good but I've noticed a couple of things that need to improve. I have added comments inline. Could you please review them and resend the pull or comment on them?

**Pull request closed without merging**
