### PR TITLE
LPS-63841 Terminating impersonation session in control panel portlet does not return user to current page

### PR DESCRIPTION
**Pull request by arbetts**
cc @drewbrokke @pei-jung

### CODE REVIEW

**Comment by arbetts** [comment]
rebase and retest

**Comment by arbetts** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37178. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
