### PR TITLE
LPS-80618 Use the terms "widget", "application" and "portlet" appropriately in UI messages

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58704. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58707. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/df53db05e611~1...df53db05e611) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
