### PR TITLE
LPS-72477 Module that automatically generates realistic users in order to have a more realistic scenarios for development & testing

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Jorge,

This pull contains the creation of all four personas defined in the doc. The next step is to populate some sample data, specifically web contents and forum threads.

/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:retest
updated branch

**Comment by JorgeFerrer** [comment]
Thanks Pei-Jung, I'll review it as soon as possible.

For the data for Web Content and Forum you should coordinate with @ealonso and @adolfopa instead of creating them yourself.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Pei-Jung, 

I've only been able to take a quick look at the pull, but it looks very good to me. Please go ahead and send it to Brian if it's ready.

**Pull request closed without merging**
