### PR TITLE
LPS-56950 Deleting an organization site removes organization roles of its users

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-56950](https://issues.liferay.com/browse/LPS-56950).<br><br>/cc @pei-jung @hhuijser

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Drew,

Great job on this, the changes are very good and the commits are very well organized. I'm just making a comment on the last commit for your evaluation.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30606. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Thank you, Jorge

**Pull request closed without merging**
