### PR TITLE
[TECHNICAL SUPPORT] LPS-91071 Log message in UserEmailAddressException.MustNotBeDuplicate is confusing and incomplete

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-91071

Hi,

Could you take a look at this? Reasoning is in the LPS description.

Br,
Norbert

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
Rebased.

Did you have a chance to look at this?

**Comment by JorgeFerrer** [comment]
Hey @NorbertKocsis, please send this pull to the User & System management team directly. I was taking some of this pulls while the team was being formed, but I had not done it for many months now.

**Pull request closed without merging**
