### PR TITLE
LPS-60477

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Jorge,
Could you take a look about this fix? it is for a ee customer

Thanks

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32362. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
