### PR TITLE
JorgesMysteriousServiceBuilder

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Jorge,

Can you you do the following?

1. ant all
2. \modules\util\portal-tools-service-builder: ant deploy
3. \portal-impl: ant build-services

You'll now see a bunch of prints in your output. Can you get that to me?

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
Hey @JorgeFerrer 

That explains why nobody but you has this problem.

Looks like your folder structure is like this:
..src/master/liferay-portal/portal-impl/src/com/liferay/..

ToolsUtil._getPackagePath got confused by this (it wasn't expecting to see "src/" twice) and messed up on returning the correct packagePath.

I sent a fix for this: https://github.com/brianchandotcom/liferay-portal/pull/28570

Let me know if that solved your issue,

Thanks,

**Comment by JorgeFerrer** [comment]
Wow, nice catch. Thanks a lot for fixing it.

**Pull request closed without merging**
