### PR TITLE
Add Rename for ScopeMapper

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
That was very fast!

Good job Marta

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59777. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
SF just caught that the commits are missing the ticket. 

All tickets need to start with the LPS, in this case https://issues.liferay.com/browse/LPS-82021
Also, in general run (cd modules && ../gradlew -b util.gradle formatSourceCurrentBranch) before sending any pull

**Comment by martamedio** [comment]
Re-submited here: https://github.com/JorgeFerrer/liferay-portal/pull/856

**Pull request closed without merging**
