### PR TITLE
LPS-68775 Cannot add an upgraded organization as parent of newly added organizations

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @mdelapenya @drewbrokke

### CODE REVIEW

**Comment by mdelapenya** [comment]
Awesome!

image

**Comment by mdelapenya** [comment]
Hi @pei-jung, could you try to execute the integration test locally?

Thanks

**Comment by pei-jung** [comment]
@mdelapenya sure, i'll take a look at the test.

**Comment by pei-jung** [comment]
Resent here https://github.com/JorgeFerrer/liferay-portal/pull/799.

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:reopen

**Pull request closed without merging**
