### PR TITLE
LPS-44467 Fix lost parameters on instanceable portlets deployed on customizable regions of layouts

### PR DESCRIPTION
**Pull request by mdelapenya**
The proposed solution takes into account that once the portlet is in the customizable region, a portlet preference will be stored for that layout and portlet. Retrieving that portlet preference for the right portletId (generated by PortletInstance class) will define if the portlet is customizable, properly setting the namespace for its specific parameters (i.e. folderId in DL). This pull includes Jorge's comments on https://github.com/juliocamarero/liferay-portal/pull/3925. cc/ @sergiogonzalez @juliocamarero @rotty3000

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
I've reviewed it but I have several doubts. We might need to sit together to review it.

However I will try to write my questions down in the commits as much as I can.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/499. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/868b845~1...868b845) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
