### PR TITLE
Lps 60527

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
see https://github.com/mhan810/liferay-portal/pull/822 for comments.  I think it's harmless but we do need to keep in mind potentially adding a 4th digit

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @lipusz @adamnagy 

Thanks for catching this and your work fixing this.

Your fix is a good start but I see some issues with it. The main one is conceptual. You are using the terminology "Qualifier" but in reality it is not working as a qualifier but works as an Snapshot qualifier which is a very special type. That was already the case before your changes but the naming you have chosen for the field (qualifier) makes it visible and thus confusing. It's a good name, but then it should really behave like a qualifier and we need to add tests for other types of qualifiers such as dates (See an example in https://wiki.eclipse.org/Version_Numbering#When_to_change_the_qualifier_segment)

**Comment by lipusz** [comment]
Hi Jorge,

Originally, Ádám wanted to consider the qualifier when we compare 2 versions, though, we cannot do this without having a list of supported qualifiers and the hierarchy between them.

So I wrote him this:

>1- SNAPHOT is a special qualifier used mainly in MAVEN projects and is usually related to continuous integration. Here's a good article: https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm

>2- Using alpha-numerical characters are allowed, though, discouraged by https://www.liferay.com/documentation/liferay-portal/6.2/development/-/ai/marketplace-basics-liferay-portal-6-2-dev-guide-11-en ("Version" section).
Without a hierarchy, neither the portal nor humans can decide the relationship between two versions.

>3- There can be other qualifiers, e.f. NIGHTLY, BETA etc. The proposed solution doesn't preserve such qualifiers.

>What I'd do is to keep the qualifiers in when constructing the toString from a Version, but doesn't use it when comparing versions. I am not aware of any documentation saying Liferay is tied to the MAVEN versioning, so the comparison should not deal with these special cases in my opinion.

What do think about these?

@JorgeFerrer

**Comment by lipusz** [comment]
Jorge,

Did you happen to read my comment above?

@JorgeFerrer

**Comment by JorgeFerrer** [comment]
Hey @lipusz, 

Sorry for the delay, yesterday was a Holiday.

What you suggest definitely makes much more sense. I would however propose a simplified version:
1) SNAPSHOT is considered special
2) Any other qualifier is considered to be in alpha numerical order

Makes sense?

**Comment by lipusz** [comment]
Hi Jorge,

Sorry for the delay, I'm attending the 7.0 trainings in LA and didn't really have the time to follow-up here.

So. I've a couple of questions:

First, when you say "SNAPSHOT is considered special", do you mean we should consider this when comparing 2 version (strings), so 1.1.0 is newer than 1.1.0-snapshot?

Secondly,
>2) Any other qualifier is considered to be in alpha numerical order

If I'm correct, any version (string) that doesn't contain the SNAPSHOT qualifier, but does any non-numeric literals should preserve in the "_qualifier" field , but should not be considered when comparing versions.

Please, correct me if I misunderstood you.

Thank you in advance!

Regards,
Tibor

@JorgeFerrer

**Comment by JorgeFerrer** [comment]
Hey, 

I'm sorry, I'm not entirely familiar with the rules for qualifiers. Can you share with me a link that describes how you think it should work?

**Comment by adamnagy** [comment]
Hello @JorgeFerrer , @lipusz ,

It was a bit long since we talked about this issue and it is in my backlog so I would like to finish this up.

I try to sum it with all the details.

There was a fix (https://issues.liferay.com/browse/LPS-57182) which completely removed the "-SNAPSHOT" qualifier from the Version object because of an issue and therefore a customer could not distinguish the installed snapshot plugins on Server Admin. These plugins maybe released by us from support.

My first attempt (https://github.com/lipusz/liferay-portal/pull/98/commits)
was to put this qualifier back to the Version's title and also consider snapshot versions lower than the not-snapshot versions.

My second attempt (this)
was to save the qualifier string but ignore it when comparing versions.


I did some research based on the links mentioned above and I found that there are 3 layers of this case.


### Layer #1 
The [LPS|https://issues.liferay.com/browse/LPS-60527] says that the issue is ONLY that a string in a version's name is lost.

To handle this, we should simply put the String back to the end of the version name when calling toString. (And ignore it to solve the originally reported issue)

Strictly speaking this is the bug (or regression) which this issue is about (https://issues.liferay.com/browse/LPS-60527)

-----

### Layer #2 
Considering SNAPSHOT a lower version than the one without this qualifier.
This would be a new feature since the portal didn't distinguish between qualifiers before.

If we go with this then there is a next level:

### Layer #3 
Considering other qualifiers when comparing versions.
This is also a feature. But in this case it is not so obvious if this is a necessary feature at all. Furthermore the other qualifiers are not always at the end of the version string: for example: 1.2-beta-2 or 1.2-rc3 (which can be considered as 1.2.2.3 - https://en.wikipedia.org/wiki/Software_versioning)

So before implementing this it must be decided whether Liferay should follow this way or not. This is a version handling mechanism which I could only see in Maven versioning system and nowhere else. (The Wiki page mentions it for the sake of completeness I guess.) Usually the build number gets a long (4 digit) number which is enough for the daily or nightly builds between versions. In Liferay, currently using a qualifier is kind of unnecessary I think.

Since we use the SNAPSHOT at our plugin releases we could handle that, but otherwise this is not an important feature. Maybe it is not even necessary.

-----

### Moving forward
As per the above and based on the discussion with Tibor I would like to suggest to push this change into Master as a bugfix and then we open a Story ticket to decide how to handle the qualifiers. Also the assignees can decide if we should handle the qualifiers at all.

**Please let me know what do you think. Can I go with opening a Story ticket then resend this change?**

Thank you in advance,
Ádám


-----


Links gathered together:
1. Eclipse versioning scheme
https://wiki.eclipse.org/Version_Numbering#When_to_change_the_qualifier_segment

2. Maven versioning scheme
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8904

3. Liferay how-to
https://dev.liferay.com/distribute/how-to-publish/-/knowledge_base/how-to-publish/planning-your-apps-distribution?notice=1

4. Liferay dev understanding versioning
https://dev.liferay.com/discover/deployment/-/knowledge_base/6-2/understanding-liferays-releases

5. Wikipedia on versioning
https://en.wikipedia.org/wiki/Software_versioning

**Comment by JorgeFerrer** [comment]
Hey @adamnagy,

Thanks for the thorough research. Based on the fact that there is no universal versioning scheme and the fact that we haven't yet had a need for more complex qualifiers I would avoid adding support for them.

The only case that we would then support is -SNAPSHOT which would be treated as an special case just like Maven does (see https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401). 
Would the solution that you describe as Layer #1 be compatible with Maven's understanding of what's an snapshot?

**Comment by adamnagy** [comment]
Hello @JorgeFerrer ,

I think so.

I created a new ticket for that since we can consider it a behavior change. I am going create the changes then resend the pull request.

https://issues.liferay.com/browse/LPS-60527
https://issues.liferay.com/browse/LPS-62383

Thank you,
Ádám

@lipusz

**Comment by JorgeFerrer** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
