### PR TITLE
LPS-54322

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-54322](https://issues.liferay.com/browse/LPS-54322).<br><br>

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
I realized I forgot to include the proper attributions in the new file (@author Scott Lee and @author Brian Wing Shun Chan).  If this passes review I want to make sure those make it in.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Please fix the issues brought up in the comments and resend.

@ealonso if you have a chance, please take a look just in case you see additional needed changes.

**Pull request closed without merging**
