### PR TITLE
LPS-53279 Replace ReservedUserEmailAddressException with inner class of UserEmailAddressException

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-53279

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Amazing job on this Pei-Jung. I specially liked how you took the initiative to convert the original exception to three inner exceptions to improve the semantics and how you documented the change in BREAKING_CHANGES :)

I'm making some minor changes and will send it to Brian

**Comment by pei-jung** [comment]
Thank you for the positive feedback, Jorge! I appreciate it. =)

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23783. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
