### PR TITLE
LPS-62459

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Thanks @arbetts. I'm forwarding this pull to the WCM team since this issue affects a portlet that they own: https://github.com/juliocamarero/liferay-portal/pull/4020

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Andrew,

I've started looking at your fix, but what strikes me is that the code you are added was not there previously but this is a new bug. 

In order to make sure this is the right fix we need to understand how it was working before. Can you dig into it?

**Comment by arbetts** [comment]
i'm sure that this is a regression bug and not a new bug since this was working in 6.2

i'll look for the LPS that changes the behavior. I suspect that it has something to do with the way we are defining which portlets are staged.

in master, all portlets are staged by default, which might not have been true in 6.2

**Comment by arbetts** [comment]
@JorgeFerrer i'll dig into the cause

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36432. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/55e5864~1...55e5864) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Andrew, 

I did some research on this myself. I still don't know why it was working before in master, but I saw that in 6.2 these portlets had an OmniadminControlPanelEntry which is the equivalente in 7.0 to your code. So your fix is correct, thanks.

What I have changed are the JSPs. See https://github.com/brianchandotcom/liferay-portal/commit/55e5864297b19d66485c77f20e597e9606041289

**Pull request closed without merging**
