### PR TITLE
[Technical Support] LPS-60205 Refine MediaWiki import logic

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Jorge,

in this version, we make an exception if and only if the MediaWiki format is supported at all and that is the default and do the conversion to Creole format in each and every other cases.

We could extend this with a checking on the format of the page that is being imported, however, only MediaWiki can be imported at this moment and as we can see, there is no implemented method to designate the format of the imported page.

As for the image links, we think that we can handle this in a simpler way than it is in the MediaWikiToCreoleTranslator class as we only need to change the path and not the complete format.

As for changing the syntax help link to JamWiki, I found an other place where we use the MediaWiki link, in the MediaWikiInterwikiLinkNode class, however, I think we should not touch that one.

Let me know if we should change anything.

Thank you in advance,
Zsigmond

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Zsigmond,

This looks much better, but I came up with one additional question, if we don't do the conversion to Creole, should we still do it when there is a redirectTitle or should we leave it as it is? If we don't want to do any conversion in that case then the code should be more like this:
````
			if (supportedFormats.contains("mediawiki") &&
						Validator.equals(
							_wikiGroupServiceConfiguration.defaultFormat(),
							"mediawiki")) {

				content = content.replaceAll(
					_imagesPattern.pattern(),
					"$1$2" + SHARED_IMAGES_TITLE + StringPool.SLASH +
						"$3$4");
			}
			else {
				if (Validator.isNull(redirectTitle)) {
					content =
						StringPool.DOUBLE_OPEN_BRACKET + redirectTitle +
							StringPool.DOUBLE_CLOSE_BRACKET;
				} else {
					_translator.setStrictImportMode(strictImportMode);

					content = _translator.translate(content);

					format = "creole";
				}
			}
```

**Comment by zsigmondrab** [comment]
Hi Jorge,

I may miss something, however as I can see that check is in the upper level condition. We are doing anything with the content only if the Validator.isNull(redirectTitle) is true, we are redirecting otherwise.

See https://github.com/zsigmondrab/liferay-portal/commit/6df298d7052c090ec58ef806abf132a870ca035e#diff-07fccae202cd4d63d3bf811c6e69ca9cL193

Am I wrong in any way?

Besides, we may have some other problem with the image links that I have to double check. I may send an other slight fix.

Thank you,
Zsigmond

**Comment by JorgeFerrer** [comment]
My first impression was exactly what you said. But then I thought about creating methods to make the code more clear and when looking at what we are doing inside "if (Validator.isNull(redirectTitle)) {" it basically looks like a conversation from MediaWiki to Creole, doesn't it?

Have you explicitly tested what would happen when importing a page that has been renamed in MediaWiki. I think that we may be converting it to Creole. Is that what we want to do in all cases?

Jorge

**Comment by JorgeFerrer** [comment]
Hey Zsigmond, 

I've been thinking about this and it's ok to always do the conversion when it's a redirect. I'm just going to make some changes to the code to make it more clear and will send it to you for a final check.

**Comment by zsigmondrab** [comment]
HI Jorge,

thank you very much. Sorry about that but I did not have time to deal with it today.

Regards,
Zsigmond

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/zsigmondrab/liferay-portal/pull/124. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/43ba1f7~5...43ba1f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
