### PR TITLE
LPS-62098 Default site role associations are not applied to the user

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung @jonathanmccann 

I don't think this is the right fix. It's changing code in the addDefaultRoles() method which is executed when the user is created (or after login in some cases) but not when a user is made member of a site. The method that should be giving the default roles is addDefaultRolesAndTeams(). If it's not doing it then it's either a bug in that method or the method is not being invoked in some circumstances when it should be.

Makes sense?

**Comment by jonathanmccann** [comment]
Hey @JorgeFerrer 

You are correct, addDefaultRolesAndTeams() does add the correct site memberships and roles to the user, however, addDefaultRoles() does not take into account these default site roles, it only looks at the globally defined default roles. When addDefaultRoles() is run through, it does not get the correct roles and then in updateUserGroupRoles() it ends up removing the default site role that was added by addDefaultRolesAndTeams().

Please let me know if I misunderstood something or if you have any questions.

**Comment by JorgeFerrer** [comment]
Hey Jon,

Thanks for the info. I don't think addDefaultRoles() should do anything (adding or removing) with the user's site roles. So if it's currently removing them then that's the bug. I think it was a bug introduced back in May with code to allow setting default site roles for all sites, so we are discussing removing that altogether with the support engineer who added it (Cledyr)

**Comment by jonathanmccann** [comment]
Hi Jorge,

Thank you for the response. Please let me know how those discussions go because I have a client waiting for a fix for this issue.

Thanks!

**Pull request closed without merging**
