### PR TITLE
LPS-115230 Update dependencies

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @JorgeFerrer 

In 28b420b I've made some cosmetic changes to make the builder methods more consistent with other map-like ones (add vs put). Feel free to remove that commit if you think it is better to keep the old names.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
Thanks Adolfo
The changes look good to me.
I've noticed that one test failed though. Could you take a look at it and if irrelevant or once fixed send it directly?

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/221

**Pull request closed without merging**
