### PR TITLE
ParamUtil Javadoc

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Jorge,

Javadoc has been provided for the entire `ParamUtil` class. Could you review it for accuracy? Thanks!

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @slemarchand,

Thanks so much for this contribution. This is super useful.

There is one thing that I wanted to discuss with you. I've noticed that you explicitly added in your second commit " or not convertible to boolean" to getBooleanParam() even after Cody had removed it the first time. I think this is wrong since this method ends up invoking GetterUtil.get() which reads as follows:

`	public static boolean get(String value, boolean defaultValue) {
		if (value == null) {
			return defaultValue;
		}

		value = value.trim();

		value = _toLowerCase(value);

		if (value.equals(BOOLEANS[0]) || value.equals(BOOLEANS[1]) ||
			value.equals(BOOLEANS[2]) || value.equals(BOOLEANS[3]) ||
			value.equals(BOOLEANS[4])) {

			return true;
		}
		else {
			return false;
		}
	}
`
Looking at this code it seems that it always returns false if it cannot be converted to a boolean.

Thoughts?

**Comment by slemarchand** [comment]
Hi Jorge,

Thanks for your accurate review.

You're right! I will fix javadoc for boolean methods (for all other types,
after double check, I think it's OK).

What do you prefer between the following 3 alternatives ?

*Choice 1*

Returns the boolean parameter from the request. If the parameter is missing,
the default value is returned.
*Choice 2*

Returns the boolean parameter from the request. If the parameter is missing,
the default value is returned. If the value is not convertible to boolean,
<code>false</code> is returned.

*Choice 3*

Returns the boolean parameter from the request. If the parameter is missing,
the default value is returned.

<p>If the value is not convertible to boolean, <code>false</code> is
returned.</p>


Which way do you prefer for the fix: I submit a new "clean" pull request or
I add a commit to the current pull request ?

-- Sébastien



2016-05-09 17:59 GMT+02:00 Jorge Ferrer <notifications@github.com>:

**Comment by JorgeFerrer** [comment]
Hey Sebastian,

Thanks for looking into this. 

I personally prefer Choice 3. @codyhoag is that separate paragraph allowed in our javadoc standards?

**Comment by codyhoag** [comment]
@JorgeFerrer yes, a separate paragraph is allowed. However, the `<p>` elements are typically on their own line. It would look like the following:

```
Returns the boolean parameter from the request. If the parameter is missing,
the default value is returned.

<p>
If the value is not convertible to boolean, <code>false</code> is
returned.
</p>
```

@slemarchand You can add an additional commit to your current branch. I'd suggest giving your commit a descriptive message to indicate your edits. Maybe something like *LRDOCS-2551 Edit ParamUtil Javadoc based on Jorge's feedback*. You can send me the pull request with Jorge's suggested edits, and I'll make sure they get merged into Liferay's *master* branch. Thanks!

**Comment by slemarchand** [comment]
@codyhoag done !

**Pull request closed without merging**
