### PR TITLE
LPS-63863 Editing an Organization after deleting its site throws NoSuchResourcePermissionException

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63863](https://issues.liferay.com/browse/LPS-63863).<br><br>/cc @arbetts @pei-jung

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @arbetts, @drewbrokke, 

This fix look like they would solve the issue, but by adding significant code complexity due to the complex if clauses. I think we need to refactor the code a little bit first so that the fix is more clear.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/arbetts/liferay-portal/pull/47. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/48b574c~2...48b574c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
I've sent @arbetts a pull request (arbetts#47) with a possible simplification.

**Comment by arbetts** [comment]
@JorgeFerrer 

see comments on arbetts#47

**Pull request closed without merging**
