### PR TITLE
LPS-53262 As a Site Admin I want to know when there's no Device Recognition Provider so that I don't waste my time creating mobile device rules

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-53262

Hey @JorgeFerrer, @natecavanaugh,

I added a check in the `<liferay-ui:error>` taglib to display warning messages. I'm not sure if it'd be worth it to create a taglib just for warning messages. Please let me know if you think we should have a separate taglib for it. Thanks!

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24417. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Beautiful pull. Thanks Pei-Jung :)

The only thing that got me thinking is that there is no documentation about this new "API" that any 3rd party developer will be able to use to show warning messages. The challenge is that there is no documentation of SessionMessages at all, so maybe we should start with that. What do you think?

**Comment by pei-jung** [comment]
Thanks, Jorge! :)

We do have documentation on SessionMessages and SessionErrors (see https://dev.liferay.com/develop/tutorials/-/knowledge_base/6-2/using-liferay-uisuccess-and-liferay-uierror-message). I will document this new API of displaying warning message there.

**Pull request closed without merging**
