### PR TITLE
LPS-52429

### PR DESCRIPTION
**Pull request by samuelkong**
Not sure if this change is something we actually want. Also, this change will affect all `name` fields, not just organization.

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Sam,

Yeah, I don't think we should change this everywhere unless we do a very careful analysis of the consequences.

Furthermore I don't think we should accept this as a bug, since it works as intended.

Do you think we could train the QA team in china to not accept something as a bug just because it can be reproduced as the reporter says, unless it's really undesired behavior?

Regarding this issue, I'm going to convert it to a Feature Request. If we get a more targeted solution I would be ok reviewing it.

**Comment by samuelkong** [comment]
> Do you think we could train the QA team in china to not accept something as a bug just because it can be reproduced as the reporter says, unless it's really undesired behavior?

This one is hard. Because I can see why they think it's a bug. The issue is in the __Users and Organizations__ section of the control panel. If you search for users, it will use the `LikeKeywordAnalyzer`. But then when you search for organizations, it requires an exact match. So I can see how this can be viewed as a bug. (Or bug is that searching for users should also require an exact match)

**Comment by JorgeFerrer** [comment]
Yup, explained that way it does make sense and I would be ok with converting it back to a bug if we explain it that way in the ticket.

In that case, could we apply to Organizations the same thing we are doing to search users?

**Comment by samuelkong** [comment]
So the change in this pull request would make organizations behave the same as users. The problem is that it affects more than just organizations. Any `name` field will be affected. This is the part that I'm really not sure if this is a change we want to make. I don't have a strong opinion either way.

**Comment by JorgeFerrer** [comment]
Hey Sam,

Exactly, but I guess for users it must have been done in a different way that affects only users, right? Could we do the same for Organizations without affecting others?

**Comment by samuelkong** [comment]
Sorry for the delay.

Users are done in the same way. It's just that `firstName`, `middleName`, and `lastName` aren't used for anything other than searching for users. However, `name` is used by many different entities other than organization (e.g., bookmarks, ddl).

I'll ask Yuxing to look into the possibility of only changing this for organizations.

**Comment by JorgeFerrer** [comment]
Hey Sam,

I see, the key problem here is that search-spring.xml is global but has info of the search behavior (to use like or not) of fields everywhere. 

I think we cannot make this change as a bug fix since it would end up being backported and it will cause unintended consequences. It can be provided as a customer fix if the customer understands the implications.

For Liferay 7 we must modularize this file so that each module can have its own definition of fields and their search behavior. At that point we will be able to fix the issue for orgs.

**Comment by samuelkong** [comment]
Ok, thanks. Let just leave the ticket as a feature request.

**Comment by JorgeFerrer** [comment]
Ok. I've just added a comment with the result of this conversation.

On Mon, Mar 2, 2015 at 10:37 AM, Samuel Kong <notifications@github.com>
wrote:

> Ok, thanks. Let just leave the ticket as a feature request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/467#issuecomment-76682223>
> .
>



-- 
Jorge Ferrer
Vice President, Engineering
@jorgeferrer <https://twitter.com/jorgeferrer>


Web <http://www.liferay.com> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>


*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Pull request closed without merging**
