### PR TITLE
LPS-63217 Virtual Instances - Unable to delete a virtual instance that contains an organization with a user assigned to it

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63217](https://issues.liferay.com/browse/LPS-63217).

@JorgeFerrer, I realize the new service method uses a control parameter, but the other option was to set the "forceDatabase" param and call the search command directly from OrganizationLocalServiceImpl, which seemed like a lot of duplicate code since we are already doing all that in the UserLocalService.  Thoughts?

<br>/cc @pei-jung @arbetts

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just fixed PMD test failure.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Closing for now.

**Comment by drewbrokke** [comment]
@JorgeFerrer UserFinderImpl does not use the InlineSQLHelper at all. That's the primary way we check permissions with a db search, correct?

**Comment by arbetts** [comment]
@drewbrokke

the InlineSQLHelper just checks for view permission, you'd have to check the joins to see if we are actually checking permissions for anything else through the DB query itself.

**Comment by JorgeFerrer** [comment]
@drewbrokke Yes, that's the way. However, as long as it's documented, I think it's ok to assume that we don't do per-user view-permission checks in this case. In the documentation we can state that if such fine grained filtering is desired it should be enabled by using the index.

In the future we should think through whether we want to disable this feature completely and not provide a UI to set different View permissions per user (and rely on organization roles instead). Also, we should consider switching the "ViewRoles" filtering from the index to the db.

Makes sense?

**Comment by mhan810** [comment]
Hm didn’t we get rid of per user based permissions everywhere else?  What’s
the issue with the view roles?



-m

**Comment by JorgeFerrer** [comment]
I will elaborate on the "view roles" staff over email.

BTW, what the status of the task you mentioned above?:

> We can try a relatively simple test of swapping out the search writer destination using a synchronous destination to see if the problem goes away.

**Comment by mhan810** [comment]
Have to get to it. Hoping to do this week. Distracted with kaleo split that
needed to be done before RC

Sent from my mobile device.

**Pull request closed without merging**
