### PR TITLE
LPS-65979 NullPointerException thrown when BackgroundTask records exist from previous run.

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65979](https://issues.liferay.com/browse/LPS-65979).<br><br>/cc @mhan810 @migue @pei-jung

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Please send to @matethurzo

**Comment by mhan810** [comment]
hm if this is for reindexing should this be in the portal-search module where the reindex sits?

@drewbrokke go ahead and send this one to me after you have made the change

**Comment by drewbrokke** [comment]
@mhan810 will do.  @JorgeFerrer I'll cc @matethurzo on my pull to Mike.

**Comment by drewbrokke** [comment]
Closing to make suggested changes and send to @mhan810.

**Pull request closed without merging**
