### PR TITLE
LPS-57182

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
I thought that the tests might be failing because of source formatting fixed in https://github.com/liferay/liferay-portal/commit/330f63c37c9a4c5ef396eecbb9c629a2c118ceb6, but looks like the last retest included it. Going to run ci:retest again to make sure.

**Comment by holatuwol** [comment]
Submitting https://github.com/JorgeFerrer/liferay-portal/pull/563 to be confident that the test failure occurs without the fix before reaching out to engineering.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28544. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @hhuijser @jonathanmccann,

I've sent the pull because it fixes the issue in the ticket, but I think this implementation is in complete because it will still not let you upgrade to a new snapshot version. For example, if you have 1.1-SNAPSHOT and you deploy a new plugin with the exact same version (1.1-SNAPSHOT) it should redeploy it. In other words, the snapshot being deployed should always be considered newer than the existing one.

Thoughts?

**Comment by jonathanmccann** [comment]
Hey @JorgeFerrer,

I am fairly certain I tested that scenario and it behaved as expected. Would you like me to test it out again?

**Comment by jonathanmccann** [comment]
I just tested it again and deploying the same WAR file will deploy on top of the previous one. I tested it by updating a text file within the WAR and seeing if the changes showed up in the deployed portlet's folder.

**Comment by JorgeFerrer** [comment]
Hey @jonathanmccann,

Ok, thanks for retesting it.
Just out of curiosity, looking at the code of Version.java I'm not sure I understand why it would work because it considers two snapshot versions as the same. Is it because the code that invokes it accepts installing the same version on top of a previously installed one?

**Comment by jonathanmccann** [comment]
Hey Jorge,

The isPreviousVersionThan method (https://github.com/liferay/liferay-portal/blob/master/portal-service/src/com/liferay/portal/kernel/plugin/Version.java#L255) checks to see if the comparison returns a value less than 0. Since the versions are exactly the same, 0 is returned, and isPreviousVersionThan returns false.

**Comment by JorgeFerrer** [comment]
You are right. Thanks for looking it up for me!

**Pull request closed without merging**
