### PR TITLE
LPS-59627

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
The shopping portlet is currently not owned by any specific team but I think @peterfellwock is the one who extracted it out as a OSGi modules. Peter, can you confirm? if so, can you review this pull?

**Comment by peterfellwock** [comment]
@JorgeFerrer this looks great, except the setUp() method on every test is failing.

**Comment by JorgeFerrer** [comment]
Thanks Peter, can you please take a look at it?

**Comment by hhuijser** [comment]
@peterfellwock thanks for the help! You want me to send this pull to you?

**Comment by peterfellwock** [comment]
@peterfellwock sure, I want to cry battling gradle for a couple of days!

**Comment by hhuijser** [comment]
See https://github.com/peterfellwock/liferay-portal/pull/90

**Pull request closed without merging**
