### PR TITLE
LPS-76235 Embedded web page nested collection resource implementation

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @ahdezma,

Can you also take a look at this pull request and provide your feedback?

What Pavel has done could potentially also serve as inspiration for improvements to Architect or as patterns to recommend as best practices in the documentation.

**Comment by ahdezma** [comment]
The APIO part seems ok to me. I've sent Pavel a suggestion for improvement in one of the utils. Other than that nothing else.

**Comment by pavel-savinov** [comment]
@JorgeFerrer Could you please take a look once again? I've just added the improvement suggested by @ahdezma [here](https://github.com/JorgeFerrer/liferay-portal/pull/834/commits/66c0995e2f1d86ba5095cc5befd7f54ca313e24f).

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Pull request closed without merging**
