### PR TITLE
LPS-62533 Portlet Permissions DoS

### PR DESCRIPTION
**Pull request by topolik**
Hi Jorge,

the logic of this fix is:
1, Extend the *default individual portlet resource* with all permissions, including defaults for site + guest roles
2, Don't create new portlet resource records for each portlet, instead rely on the defaults << this should also fix the phantom reads (https://issues.liferay.com/browse/LPS-55605)

When we check portlet permissions
- we try to find `plid_LAYOUT_ppid` specific records. If they exist, it means that admin configured the portlet manually (or we upgraded from previous LR version)

If no such records exist, we fallback to the *default individual portlet resource* records, from the defaults we use: 
(A) GUEST role assignments
(B) SITE_MEMBER / ORGANIZATION_MEMBER roles assignments, based on the place where the portlet is present

Thanks

https://issues.liferay.com/browse/LPS-62533

### CODE REVIEW

**Comment by topolik** [comment]
Rebased

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
The test failure is unrelated, can be also seen here: https://github.com/brianchandotcom/liferay-portal/pull/35024

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/jorgeferrer/liferay-portal/pull/648. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1126. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/272. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/774e951~5...774e951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
