### PR TITLE
LPS-64240 Defining permissions summary page has the redirect URL and the 'Remove' link misaligned on Wildfly 10.0.0

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-64240](https://issues.liferay.com/browse/LPS-64240).

This is a fix for our component, but the underlying issue is still present. @migue this is where the issue comes from: https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/search/JSPSearchEntry.java#L80-L83.  I passed in the servletContext to the `addJSP` method call to circumvent that code.

/cc @pei-jung

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Drew,

Thanks for finding a fix.

I would prefer to wait and not solve it that way (at least not yet), because we would be leaving the problem everywhere else where we are invoking row.addJSP(), and there are tons of places where we are doing that.

Are you ok with waiting until we find a definitive solution? If the GA2 date approaches and we don't have a final solution I'm ok if you send this pull then.

**Comment by drewbrokke** [comment]
Yes that makes sense.  Just FYI, I only found one other place where `row.addJSP` was [called without a servletContext](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/announcements/announcements-web/src/main/resources/META-INF/resources/view_manage_entries.jspf#L120).  Everywhere else was fine.

**Comment by JorgeFerrer** [comment]
How about when it's used through the taglib?

If the solution is really this one, we should depracate and later remove
the method without all parameters.

**Comment by drewbrokke** [comment]
The taglib [automatically adds the servletContext](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/SearchContainerColumnJSPTag.java#L63).  Everywhere I checked, there were no issues when using the taglib.

That being said, I still think this is a partial solution, and I wonder if this issue would end up showing up in some other context.  I haven't been able to find anything yet about what's really happening, but at least this kind of fix will effectively avoid the issue for now. 

I did think about deprecation - it would make a lot of sense since I don't think there's a case where you wouldn't have those additional arguments available to you.

**Pull request closed without merging**
