### PR TITLE
LPS-54752 Adapt Bookmarks to GroupService/PortletInstanceSettings and GroupService/PortletInstanceSettingsProvider removal.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
/CC @jkappler See commit ded8042 with changes to RSS portlet

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/100. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/1199106d~5...1199106d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
