### PR TITLE
LPS-65497 UserLocalServiceImpl.updateModifiedDate doesn't set modifiedDate

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65497](https://issues.liferay.com/browse/LPS-65497).<br><br>/cc @NorbertKocsis @lipusz @pei-jung @Preston-Crary

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Drew,

Your additional changes may interfere with Norbi's another fix that is also in review: https://github.com/lipusz/liferay-portal/pull/130.

@drewbrokke

**Comment by lipusz** [comment]
@NorbertKocsis : since I'll be OoO next week, you can forward lipusz#130 to Drew also.

**Comment by Preston-Crary** [comment]
I think the test failure means you just need to run the ServiceBuilder, but not totally sure.  The other change from Drew means that https://github.com/lipusz/liferay-portal/pull/130/commits/1762b87cd8d00633084e24eb3e5f4708ef484786 can just be excluded from the pull.

**Comment by lipusz** [comment]
I wouldn't touch LDAP stuffs under this LPS. This complicates history and
tracking complicated. This LPS is about a service that doesn't do what it
states. LDAP should be addressed separately imho.

On Fri, May 6, 2016 at 11:12 PM, Nathaniel Preston Crary <
notifications@github.com> wrote:

> I think the test failure means you just need to run the ServiceBuilder,
> but not totally sure. The other change from Drew means that lipusz@1762b87
> <https://github.com/lipusz/liferay-portal/pull/130/commits/1762b87cd8d00633084e24eb3e5f4708ef484786>
> can just be excluded from the pull.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/733#issuecomment-217559604>
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by drewbrokke** [comment]
@Preston-Crary you're right - I left the ServiceBuilder changes off accidentally.

@lipusz I see your point.  I'll re-submit without my changes, but I think we should use those changes in the relevant ticket.  We eliminate a couple of persistence calls that way.

**Comment by lipusz** [comment]
@NorbertKocsis: please make sure you adjust lipusz#130 as Drew requested
before sending to him.

@drewbrokke: thanks!

On Fri, May 6, 2016 at 11:20 PM, Drew Brokke <notifications@github.com>
wrote:

> @Preston-Crary <https://github.com/Preston-Crary> you're right - I left
> the ServiceBuilder changes off accidentally.
>
> @lipusz <https://github.com/lipusz> I see your point. I'll re-submit
> without my changes, but I think we should use those changes in the relevant
> ticket. We eliminate a couple of persistence calls that way.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/733#issuecomment-217561263>
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by drewbrokke** [comment]
Closing in favor of JorgeFerrer#734

**Comment by drewbrokke** [comment]
Thanks @lipusz!

**Pull request closed without merging**
