### PR TITLE
LPS-61779 OrganizationLocalService.hasUserOrganization throws NullPointerException when inheritSuborganizations and includeSpecifiedOrganization params are true

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-61779](https://issues.liferay.com/browse/LPS-61779).<br><br>/cc @pei-jung @lipusz @djavorszky @hhuijser

### CODE REVIEW

**Comment by drewbrokke** [comment]
Closing to add test

**Comment by lipusz** [comment]
Regarding the test: I've already asked Daniel to add:
https://github.com/hhuijser/liferay-portal/pull/2598#issue-125941360

@drewbrokke

Sent from mobile
--
Senior Software Engineer
Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global

**Comment by lipusz** [comment]
So please notify him if you'll cover it to avoid duplication of work.😉

Thx,
Tibor

Sent from mobile
--
Senior Software Engineer
Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global

**Comment by drewbrokke** [comment]
Hey @lipusz, that should be fine to let him write the tests.  Shall I reopen this pull or wait for the tests?

**Comment by lipusz** [comment]
I'd prefer to reopen this and pass it forward, we can push the changes in a
new pull afterwards if this is suitable for you and Jorge.

Sent from mobile
--
Senior Software Engineer
Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global

**Comment by drewbrokke** [comment]
Sounds good. Reopening.

**Comment by drewbrokke** [comment]
@lipusz, something like this?

```
LinkedHashMap<String, Object> params = new LinkedHashMap<>();

params.put("usersOrgsTree", organizationsTree);

if (!ListUtil.isEmpty(organizationsTree) &&
	userFinder.countByUser(userId, params) > 0) {

	return true;
}
```

**Comment by lipusz** [comment]
@drewbrokke

I'd move the declaration of the LinkedHashMap into the if-block where we
only get into if the organizationsTree is not empty.

Sent from mobile
--
Senior Software Engineer
Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global

**Comment by drewbrokke** [comment]
Got it.  More like this:

```
		if (!ListUtil.isEmpty(organizationsTree) {
			LinkedHashMap<String, Object> params = new LinkedHashMap<>();

			params.put("usersOrgsTree", organizationsTree);

			if (userFinder.countByUser(userId, params) > 0) {
				return true;
			}
		}
```

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey guys, 

Thanks for finding this bug and working on fixing it. Looking at the code I realized that it fixes a second case not documented in the ticket so I created a second ticket: https://issues.liferay.com/browse/LPS-62204

This made me realize how badly we need tests for this method. @djavorszky were you able to work on writing the test or do you prefer @drewbrokke to do it?

I would prefer to have the test before sending the pull to master, but I would want to do it this week.

**Comment by JorgeFerrer** [comment]
Closing the pull temporarily until the test is added

**Comment by lipusz** [comment]
The tests are on the way: https://github.com/lipusz/liferay-portal/pull/104/
I'll forward it to you shortly.

On Tue, Jan 19, 2016 at 1:26 AM, Jorge Ferrer <notifications@github.com>
wrote:

> Closing the pull temporarily until the test is added
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JorgeFerrer/liferay-portal/pull/631#issuecomment-172691495>
> .
>



-- 

*Tibor LIPUSZ*

Sr. Software Engineer, Team Lead
SME of Search & Security
Subscription Services, EMEA


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by lipusz** [comment]
See: https://github.com/JorgeFerrer/liferay-portal/pull/633

**Pull request closed without merging**
