### PR TITLE
LPS-54664

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Jorge,
@arbetts asked me to send this over to you. Let me know if you have any questions.

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36877. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @natecavanaugh @arbetts,

Thanks both for your work on this. I reviewed the result and it is much better than what we had. I think there is still room for improvement (such as maybe use AJAX, or at least scroll down with an anchor after the page refresh when clicking an "Index" button). But considering the time limitations I'm good with this.

@mhan810 You may want to look at the code. I went over it and it made sense to me, but I'm not an expert in Background Tasks.

**Comment by mhan810** [comment]
looks ok

**Pull request closed without merging**
