### PR TITLE
LPS-68695 RequiredUserGroupException error is thrown when trying to delete a User Group or Organization with API

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @JorgeFerrer,

Using database for searching user counts instead of indexer since reindexing is executed on a separate thread, indexed results might not be searchable immediately. This leads to inconsistency when getting user counts in the user group or organization right after reindexing.

/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung,

One thing I wonder with this pull is, shouldn't the fix be to not use the index for any count? 
I mean, by looking, for example, at the method signature or javadoc of userLocalService.getUserGroupUsersCount() it's clearly not obvious that it would have this side effect due to an implementation aspect (using the index).

Do you know why it's using the index? If there is really a good reason, we should explain it in the javadoc.

**Comment by pei-jung** [comment]
Hey @JorgeFerrer,

We don't want to change the get count method directly because it might cause a regression. It was switched from db search to indexer due to performance issues (see [LPS-45530](https://issues.liferay.com/browse/LPS-45530)).

I agree with the changes in this pr because i think it makes sense. The `delete` method should work whether index has been enabled or not. Yet, there's no way to know if a reindex has been triggered and finished before the `delete` operation. To make sure we get the most up-to-date count of the users before continuing the operation, we should use the finder.

I think we should document this side effect of using index. The devs should be aware that the indexing operation is asynchronous, so that indexed results might not be immediately searchable. However, if needed, they can force synchronous indexing by using `ProxyModeThreadLocal.setForceSync(true);` (see [example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/portlet/action/EditOrganizationAssignmentsMVCActionCommand.java#L97-L104)).

**Comment by JorgeFerrer** [comment]
Thanks for the explanation Pei-Jung. It makes sense.

Please go ahead and submit the solution as it is to Brian.
And also keep a mental note (or maybe add it to the Lines of Work doc) so that we do a full review of our usage of db vs index for 7.1

Sounds good?

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/44366

**Pull request closed without merging**
