### PR TITLE
LPS-68951 UserFinderImpl.countByC_FN_MN_LN_SN_EA_S is slow in case of using database instead index and having a lot of users

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-68951

From @jorgediaz-lr 

> Sybase has some problems with select count from a union:
> select count(c) from ((select c from table1) union (select c from table2))
> 
> To avoid sybase limitation I have added following commit: 597d285
> 
> This approach is similar to UserFinderImpl.countByGroups added in LPS-57748: brianchandotcom#30280

/cc @jorgediaz-lr @drewbrokke

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Hey Pei-Jung,

I'm not familiar enough with this code or DB optimization to be a good reviewer of this code. I think it's better if you ask Shuyang who would be a good reviewer for it.

Thanks!

**Comment by pei-jung** [comment]
Hi Jorge,

I sent it over to Shuyang for review https://github.com/shuyangzhou/liferay-portal/pull/3438.

**Pull request closed without merging**
