### PR TITLE
LPS-63476 Fixes My Contacts broken link

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63476](https://issues.liferay.com/browse/LPS-63476).

@JorgeFerrer, this removes the link completely if the ContactsCenter portlet is not on the user's site.  Otherwise we end up with weird UX where it renders the Contacts Center portlet with no clear navigation back to the My Contacts portlet (besides the browser's back button).

/cc @pei-jung

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Drew,

The code looks good, but please create a ticket of type bug for it. We should not reuse tickets that are already closed.

**Comment by drewbrokke** [comment]
Ah my mistake.  Sending you a new pr under the new ticket.

**Comment by drewbrokke** [comment]
New pull request: JorgeFerrer#704
New Issue: https://issues.liferay.com/browse/LPS-64943

**Pull request closed without merging**
