### PR TITLE
LPS-63145 Liferay 7 always uses the database to search for organizations

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Jorge,

We will force the search to use database when the search params contain unindexed fields (i.e. organizationsRoles when assigning organizations to roles), or when the request requires huge index updates (i.e. adding many organizations at once). Otherwise, searching organizations will use indexer by default when indexer is enabled for performance reasons. Let me know if there's any issues. Thanks!

/cc @drewbrokke

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Pei-Jung,

Can you share your reasoning for switching from useIndexer to forceDatabase?
One initial concern I have is that user-search-container-results and user-group-search-container-results still have a useIndexer attribute. Should they be changed to?
Also, if we make this change we are breaking backwards compability. It may not be a big deal since this taglib should not be widely used outside of Liferay's own portlets, but we should still document it.
Finally, why is it necessary to force using the database for user & organizations admin? Shouldn't we use the search always for text searches and the database for filters?

**Comment by pei-jung** [comment]
Hey Jorge,

I switched the name to forceDatabase because I feel the name useIndexer is a bit confusing. There are already properties that define whether to use indexer or not. What this attribute does is to allow force using the database even when indexer is enabled via the properties. I think changing the name makes more sense to the user. This will not cause backward compatibility issue because these taglibs were created during the osgi migration. And you're right. There are still other taglibs that have the useIndexer attribute. I'll change them too if you think the change is good.

It's not necessary to force using database for users and organizations admin. That's why by default the forceDatabase attribute is false. We want to force using database when we need to filter results on unindexed fields.

**Comment by drewbrokke** [comment]
I agree with @pei-jung.  `forceDatabase` is more accurate in describing what is happening than `useIndexer` was (it was not guaranteed to use the indexer if `useIndexer` was true).  And if we do make the change, I definitely think we should apply it to all similar taglibs.

**Comment by JorgeFerrer** [comment]
Thanks for the explanations. It makes sense :)

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36264. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
