### PR TITLE
LPS-68775 Cannot add an upgraded organization as parent of newly added organizations

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @JorgeFerrer,

Looking at the code, the current behavior for adding/updating org is that if it finds a type not specified in portal.properties, it throws a `OrganizationTypeException`. I don't think we want to change the behavior because it might cause unexpected behaviors and bugs. Unrecognized organization types only occur in manual modification in the db or import from somewhere else; it's impossible to add an unspecified type from the UI since we're generating the types from portal property and populate them as a dropdown. If the data is from old versions of liferay, the upgrade process should be run. If the data is imported somewhere else, it should be imported properly by updating the associating properties accordingly.

Since the issue addressed in the ticket is with upgrade, I'll just keep the changes related to upgrade process only. The changes are the same as https://github.com/JorgeFerrer/liferay-portal/pull/799.

/cc @mdelapenya @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Makes sense. Thanks for thinking it through.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45055. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
