### PR TITLE
LPS-65056 Export of users to CSV does not work

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung, @drewbrokke,

Good job on the review, those are good changes.

There is also a lesson to learn from this pull. To follow the semantic versioning rules Pavel was not able to just change the ActionCommand into a RenderCommand  because that class was considered a public API and thus such a change would have required a major API change.

This is happening because the module is currently exporting com.liferay.users.admin.web.* This is dangerous because you end up exporting more classes (such as commands) than you really want to make a public API.

This is a good experience to be more strict with what is exported in the future. Also for this module (and others were we might be doing the same) we will need to "fix" them in the future to export only what we really want to expose as a public API. Makes sense?

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38910. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
That makes a lot of sense.  Now that semver is in place I can see how it really makes a difference to carefully choose your exports rather than tossing an asterisk on the end and walking away.

**Pull request closed without merging**
