### PR TITLE
LPS-66240 As a roles admin I would like to be guided when creating a role through choosing a name, defining the permissions and assigning the first users

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
@JorgeFerrer if this passes, we need to send to @alee8888 to update the functional tests.  Thanks!

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42899. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung @drewbrokke,

Good job on this pull. I think the code is good so I've submitted it to Brian.

I've also done a PM Review and have added some suggestions for improvements in the JIRA ticket.

**Pull request closed without merging**
