### PR TITLE
LPS-72477 As a developer, I'd like to automatically generate personas in order to have a more realistic scenario for testing

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Jorge,

The users-admin-demo module creates the site, the site admin (Helen), and the virtual instance admin (Bruno) when deployed. Let me know what you think. I'll keep working on adding the rest of the personas

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Closing for now, since I'm not sure if you want me to forward this to Brian.

**Comment by pei-jung** [comment]
Hey @JorgeFerrer,

If everything looks good, I'll send it to Brian. I want to send the changes in small pulls so it's easier for Brian to review, and hopefully can get merge in quicker. The next pull will contain changes to add the remaining personas.

**Comment by JorgeFerrer** [comment]
Got it. Please go ahead.

**Comment by pei-jung** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/49032.

**Pull request closed without merging**
