### PR TITLE
LPS-48156 Apply inner exceptions pattern to PrincipalException

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Jorge,

Here is my progress on PrincipalException so far. It's not complete yet but I'd like to have a preliminary review from you to make sure everything look good. I've replaced most PrincipalException throws clauses with inner classes. There are about 10 files left that I'm not sure what the exception is about:

`AssetPublisherConfigurationAction.java`
`AssetPublisherUtil.java`
`SaveActionCommand.java`
`ActionUtil.java`
`PortletAction.java`
`AnnouncementsFlagServiceImpl.java`
`EditLayoutsAction.java`
`CreateAnonymousAccountAction.java`
`MBBanServiceImpl.java`
`SitesImpl.java`

As for JSP usages update, it is actually more complicated than I had expected. For exceptions thrown in the service classes, how can I track which JSPs will be affected so that I can catch and display the exceptions properly? I need some guidance here, thanks!

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Great job in this pull Pei-Jung. It was a hard one :)

I've added some comments and will also send you a pull with some changes I've done for your review.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/pei-jung/liferay-portal/pull/32. [See changes here.](https://github.com/JorgeFerrer/liferay-portal/compare/34dca44~3...34dca44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Here is my advice on the classes that you have doubts about:
AssetPublisherConfigurationAction.java, AssetPublisherUtil.java, SaveActionCommand.java, PortletAction.java --> These classes should not throw PrincipalException. Instead it should have a InvalidConfigurationException which is not a subclass of PrincipalException. What do you think?

ActionUtil.java --> Which package?

AnnouncementsFlagServiceImpl.java --> this is an interesting case. Basically this entity can only be deleted by the current user. What do you think of creating an exception called MustBeOwnedByCurrentUser() or something like that?

EditLayoutsAction.java --> For most usages MustHavePermissions should work. The one in line 366 is a bit more complicated. Maybe something like MustInitializeGroup?

CreateAnonymousAccountAction.java --> For the one in line 82 I would create MustHaveStrangersEnabled(Company) and mention the company.security.strangers property
For the one in line 88 maybe we can create a MustBeAllowedPortlet or MustBeValidPortlet and pass (currentPortletName, validPortletName)

MBBanServiceImpl.java --> Maybe something like MustNotBeGroupAdmin(String resourceName, long resourceId, String ... actionId)

SitesImpl.java --> The one in line 499 should be MustHavePermission, maybe splitting the if in several. The others look like cases of MustHavePermission as well.

Let me know what you think.

**Comment by pei-jung** [comment]
> AssetPublisherConfigurationAction.java, AssetPublisherUtil.java, SaveActionCommand.java, PortletAction.java --> These classes should not throw PrincipalException. Instead it should have a InvalidConfigurationException which is not a subclass of PrincipalException. What do you think?

I agree. These exceptions do not belong to PrincipalException. I will create a new exception class (`ConfigurationException`?) and subclasses for each specific causes.

> ActionUtil.java --> Which package?

liferay-portal/modules/apps/wiki/wiki-web/docroot/WEB-INF/src/com/liferay/wiki/web/wiki/portlet/action/ActionUtil.java

This one doesn't look like a PrincipalException either. It looks more like an invalid configuration exception to me.

> AnnouncementsFlagServiceImpl.java --> this is an interesting case. Basically this entity can only be deleted by the current user. What do you think of creating an exception called MustBeOwnedByCurrentUser() or something like that?

Sounds good. Will do.

**Comment by JorgeFerrer** [comment]
ConfigurationException sounds good to me.

Regarding the wiki ActionUtil I agree that it's not a permissions exception. Not sure if it's a configuration issue though. Maybe you can leave it as it is and let @sergiogonzalez decide what to do with it.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/JorgeFerrer/liferay-portal/pull/544.

**Pull request closed without merging**
