### PR TITLE
LPS-53969

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @JorgeFerrer,

See https://github.com/hhuijser/liferay-portal/pull/2311 for a bit more info on this one

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Hugo @drewbrokke,

I'm a bit confused by this pull and the associated description in JIRA. I just don't see a match between the information in the ticket and the fix. In the ticket it says that the expected result is to delete the user group but all the fix is doing is disabling the checkbox when the user doesn't have permission. But should he have them? Please update the ticket accordingly if the code change is really correct.

One other thing that confused me is the changes to sites_admin. How is sites admin related to user groups? I don't understand it.

**Comment by hhuijser** [comment]
@JorgeFerrer

Regarding the changes to sites_admin. All I did there, was move the current class UserGroupChecker to sites_admin, because that's the portlet that's actually using it (sites_admin/edit_site_assignments_users.jsp).
This allowed us to create a new UserGroupChecker in usergroupsadmin that we needed for this fix.

@drewbrokke can respond to the other question.

**Comment by JorgeFerrer** [comment]
Hey Hugo,

Thanks for your answer. However I'm not sure I understand it. I don't see any modification to sites_admin/edit_site_assignments_users.jsp and that JSP is part of the membership management of sites which doesn't list user groups. Am I missing something?

**Comment by drewbrokke** [comment]
Hi @JorgeFerrer, thanks for pointing out that the ticket description does not match the fix.  I have updated the ticket description.

**Comment by hhuijser** [comment]
Hey @JorgeFerrer

The className is confusing...
The class UserGroupChecker is in fact not dealing with userGroups, but rather with Users and Groups.
It is following our naming convention though. See UserOrganizationChecker.java or UserPasswordPolicyChecker.java.

Anyway... @drewbrokke, are you going to resend or should we reopen this pull?

**Comment by JorgeFerrer** [comment]
Hey Hugo,

I can reopen the pull, but I don't think you are right in your comment above.

The ticket clearly refers to UserGroups and the User Groups Administration portlet. The code of UserGroupChecker clearly deals with UserGroups. And it is clearly applied to  portal-web/docroot/html/portlet/user_groups_admin/view_flat_user_groups.jspf in the commit https://github.com/hhuijser/liferay-portal/commit/811cba1c26286c9e00d783a3c982ffb8e42e1cdf

Are you sure we are talking about the same pull? Please ping me on skype if I'm missing something.

**Comment by JorgeFerrer** [comment]
For the record I talked to Hugo and the confusion came from the fact that there was previously a class called UserGroupChecker.java that was wrongly placed in the package for UserGroups admin but in reality it was used from Sites Admin to deal with the relationship of users with groups. So Hugo is moving that class to its proper location in his commits and leaving the new class where that one used to be.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24755. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
