### PR TITLE
LPS-62006 Rendering a user search happens faster than user indexing can complete

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-62006](https://issues.liferay.com/browse/LPS-62006).

Hey @JorgeFerrer, this returns the user searches to their original state (using the indexer by default). Now that @mhan810 has provided a way to force the indexer to complete synchronously, we're simply wrapping troublesome method calls in the try-resource block.  Let me know if you have any questions.  Thanks!<br><br>/cc @pei-jung @arbetts

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @pei-jung,

I'm ok with that considering that the db search does not have permission filtering. But I still think that the index should only be used when doing keywords based searches (or any other search where the index is really necessary). Please keep it in mind for the future.

Regarding the code it looks good to me except for one thing. In the last two commits the code added is surrounded by try clauses with no catches or finally. Were there suppose to be a finally clause? Else, should the try clauses be removed?

Once you've solved this go ahead and send to Brian directly.

**Comment by pei-jung** [comment]
Hey @JorgeFerrer,

Isn't it more preferable to use index for search when there's huge volume of data? For companies with lots of users/organizations, searching for users/organizations with db will significantly impact the performance. This issue is brought up in [LPS-63145](https://issues.liferay.com/browse/LPS-63145).

And as Mike Han pointed out, the try-with-resources statement will make sure the ProxyModeThreadLocalCloseable is closed at the end of the try block since it's a closeable. So the finally clause is not needed. I'll go ahead and send this to Brian.

**Comment by pei-jung** [comment]
PR sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/37219.

**Pull request closed without merging**
