### PR TITLE
LPS-63476 Extract Contacts Portlet to OSGi Module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63476](https://issues.liferay.com/browse/LPS-63476).<br><br>/cc @pei-jung @arbetts

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke,

Amazing job on this, I'm impressed :)

I'm closing it because I have some comments/questions to make, but they are minor, so feel free to send the pull directly to Brian after answering them:

1) Why is the chat portlet included in here? It should not be.
2) I'm not a big fan of having so many JSPs at the root level. I think they should be inside a contacts-center folder since there is one folder for every other portlet. However I understand that you are just copying the existing dir structure, so I'm ok with it if Brian is.
3) Upgrade process. Just like I mentioned for contacts-center-service I'm not sure this will ever work. Did you check with Jon Lee?
4) Why is there a dependency on contacts-service? Ideally it should only depend on contacts-api. Is it because of any specific class that could be moved over to -api?
5) What's the impact of the social-office-disabled CSS class?. Since it's no longer being used, has social-office-enabled been removed from the CSS?

**Comment by drewbrokke** [comment]
Thanks @JorgeFerrer, I'll make these changes today.

**Comment by drewbrokke** [comment]
Hey @JorgeFerrer!  Here are my responses to your points so far:

> 1) Why is the chat portlet included in here? It should not be.

I have removed it.

> 2) I'm not a big fan of having so many JSPs at the root level. I think they should be inside a contacts-center folder since there is one folder for every other portlet. However I understand that you are just copying the existing dir structure, so I'm ok with it if Brian is.

I think it would be nice to re-structure this, though for the purpose of getting this through, I think we can leave it for now and re-structure after it's merged.

> 3) Upgrade process. Just like I mentioned for contacts-center-service I'm not sure this will ever work. Did you check with Jon Lee?

Maybe I don't understand what is holding this up.  This seems like a straightforward upgrade of portlet keys.  Could you explain your thinking a little further?  I feel like I'm missing something...

> 4) Why is there a dependency on contacts-service? Ideally it should only depend on contacts-api. Is it because of any specific class that could be moved over to -api?

I have moved the dependency into contacts-api.

> 5) What's the impact of the social-office-disabled CSS class?. Since it's no longer being used, has social-office-enabled been removed from the CSS?

Thanks for catching that.  It is no longer necessary.  I have removed it.

**Comment by JorgeFerrer** [comment]
Hey Drew,

Here are my answers:
1) Thanks!
2) Sounds good.
3) I just don't think this upgrade process will be enough to upgrade an old installation of Social Office. That's why I asked you to check with Jon. If he thinks it could, we should try to test it.
4) Thanks
5) My pleasure :)

**Comment by drewbrokke** [comment]
Ok.  Regarding the upgrade, could we also improve it after everything else gets merged? It seems like it will take a bit of legwork to make sure all cases are covered by the upgrade.  Is it a deal-breaker to merge it as is?

**Comment by JorgeFerrer** [comment]
Yes, you can do it after, but please don't forget.

**Comment by johnnyhowey** [comment]
Hi @JorgeFerrer 
Regarding to the upgrade process, I am not sure what the old social office is going to upgrade into? I think until we know what that is, I am not sure what to look at.

Drew mentioned that we might need to upgrade the portletId in any of the SO specific table. I can start looking into it, but are all the porteltIds saved in any portal table going to be upgraded by the portal upgrade process? For example, if contact center sent an notification using the old contact center portletId, notification upgrade process should already handle it right?

I think we might have to merge this first, and test later. Let me know if you have any concern

**Pull request closed without merging**
