### PR TITLE
LPS-63475 Extract Contacts Service to OSGi Module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63475](https://issues.liferay.com/browse/LPS-63475).<br><br>/cc @pei-jung @arbetts

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
FYI @JorgeFerrer: I just pushed a change that fixes the SF error.  Please re-pull for review.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36878. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
