### PR TITLE
[TECHNICAL-SUPPORT] LSP-53055

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-53055

Hi Jorge,

This is outcome of the forum discussion with László. Details on the LPS.

Regards,
-tibor

/cc @hudakl

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hey Jorge,

I was just wondering if you had the time to review this pull.
Thank you for the update,
-tibor

**Comment by lipusz** [comment]
Rebased.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23844. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
