### PR TITLE
LPS-54956

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-54956](https://issues.liferay.com/browse/LPS-54956).<br><br>Hey Jorge, these are the changes updating how required user name fields are handled in portal. It also removes the use of users.last.name.required from portal. Let me know what you think of these changes.  Thanks! @pei-jung @natecavanaugh

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke, Please review the failed tests, it seems they could have something to do with your changes. In any case I'll force CI to run them again just in case.

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by drewbrokke** [comment]
@JorgeFerrer, I rebased and ran ant test-integration locally, and it completed successfully.  I'll send again.

**Comment by drewbrokke** [comment]
I ran into a different error, and I'm not sure if it was caused by my changes or not.  I'm closing for now until I can confirm I didn't cause it.

**Pull request closed without merging**
