### PR TITLE
GetterUtil Javadoc

### PR DESCRIPTION
**Pull request by codyhoag**
Hi Jorge,

Could you review this `GetterUtil` Javadoc submitted by @slemarchand? Thanks!

https://issues.liferay.com/browse/LRDOCS-2583

### CODE REVIEW

**Comment by cgoncas** [comment]
Hi @codyhoag ,

I will review it.

**Comment by JorgeFerrer** [comment]
Thanks Cristina!

**Comment by codyhoag** [comment]
@cgoncas would you like me to send you a pull request?

**Comment by cgoncas** [comment]
Hey @codyhoag ,

I'm reviewing Jorge's pull, have you made any change?

**Comment by codyhoag** [comment]
@cgoncas sounds good! No changes from me :smiley:

**Comment by cgoncas** [comment]
Hey @codyhoag ,

I've finished the review. It is in https://github.com/codyhoag/liferay-portal/pull/57

**Comment by codyhoag** [comment]
Thanks, @cgoncas!

**Pull request closed without merging**
