### PR TITLE
LPS-47907 All users listed in Users page regardless of permissions when querying outside of any organization

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @JorgeFerrer,

I tried to add a new constant for `NO_ORGANIZATION_ID` in `portal-kernel/src/com/liferay/portal/kernel/model/OrganizationConstants.java` but ran into some issues with semantic versioning. Adding a new constant to a class in the com.liferay.portal.kernel.model package requires a minor version increase as reported by the baseline. After making the version change, it breaks a lot of other bundles. The problem is because com.liferay.portal.kernel.model package contains a lot of `@ProviderType` classes. If we change the minor version of this package, then every provider of that package has to import the new package. Otherwise, they cannot be resolved due to incompatibility with the available package. To fix it, we'll need to manually update the version to `default` in those bundles.

My question is: do we want to add the new constant to the `OrganizationConstants` class in com.liferay.portal.kernel.model and try to fix the versioning issues? or should we avoid making any changes to portal.kernel?

/cc @drewbrokke

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38981. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Ok, let's leave it this way for now. However I would like this to be added in a list of Technical Debt somewhere so that we don't forget. Any suggestion for how to keep track of it?

**Comment by pei-jung** [comment]
We can create a ticket for this and backlog it. I'll check with Josh to see what he suggests.

**Pull request closed without merging**
