### PR TITLE
LPS-57385 create individual scope resource for root resource when it doesn't exist

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/2. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
