### PR TITLE
LPS-58995 Fix rebase

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey Jorge, this is the rebased version.

Let me know what your thought are so I can update this pull.

Thanks

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey @marcellustavares @brunobasto Great job on this, it's a really cool feature. I suggested a few improvements to Marcellus yesterday that I hope won't be very difficult to implement. 

Feel free to send me a pull once they are done.

**Comment by brunobasto** [comment]
Thank you, @JorgeFerrer! It was ll thanks to @leoadb

**Comment by JorgeFerrer** [comment]
Good job @leoadb ! :)

**Comment by leoadb** [comment]
Thanks @JorgeFerrer !

**Pull request closed without merging**
