### PR TITLE
LPS-67890 Exported multi-value settings appear in separate lines

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
Nice job on the changes, @pei-jung!

**Comment by pei-jung** [comment]
Support to add comments in .config file is added in [org.apache.felix.configadmin-1.8.8](http://svn.apache.org/repos/asf/felix/releases/org.apache.felix.configadmin-1.8.10/changelog.txt).

Currently, fileinstall still uses an old version of configadmin. The [latest one 3.5.4](https://gist.github.com/pei-jung/043f5d1177a7086634990914e62fb2df#file-pom-xml-L56-L58) uses version 1.2.8 of the configadmin. However, felix has updated fileinstall to use configadmin-1.8.8 commited in their [trunk](https://svn.apache.org/repos/asf/felix/trunk/fileinstall/pom.xml). We can start adding comments in .config files when the new version of fileinstall is released.

**Comment by JorgeFerrer** [comment]
Hey @pei-jung, 

Even though the pull was closed I did a quick review and it looked good. I just missed some tests.

**Comment by lipusz** [comment]
https://github.com/pei-jung/liferay-portal/pull/139

**Pull request closed without merging**
