### PR TITLE
[TECHNICAL SUPPORT] LPS-56888 A role's defined permissions for a portlet are removed when ADD_DISPLAY_TEMPLATE is granted under Application Display Templates

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56888

/cc @NorbertKocsis

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased to latest HEAD

**Comment by lipusz** [comment]
Hi Jorge,

I just wanted to le you know that I'm going for a holiday next week, so please, turn to @NorbertKocsis directly if you had any concerns.
Otherwise, please, push it forward as soon as you have the time, since it's already provided as an SDH fix for a Subscriber and we want to avoid creating backlog.

Rebased to latest HEAD.

Thanks,
Tibor

@JorgeFerrer

**Comment by JorgeFerrer** [comment]
OK, thanks. Enjoy your vacation.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28625. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
