### PR TITLE
LPS-55590 Convert Users Admin and My Account portlets to MVCPortlet

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @natecavanaugh

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Pei-Jung,

I reviewed the pull and overall I think it's good. However the change you did in the previous to last commit I think is wrong. I've written a comment next to it.

Once this is fixed you can go ahead and send it to Brian directly.

**Comment by pei-jung** [comment]
Pull request submitted to Brian https://github.com/brianchandotcom/liferay-portal/pull/28448.

**Pull request closed without merging**
