### PR TITLE
LPS-66239 Apply lexicon improvements to Password Policies

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Jorge,

I made the changes based on the comments you made in the ticket. https://issues.liferay.com/browse/LPS-66239.

/cc @drewbrokke

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Great job Pei-Jung, everything I mentioned is fixed now. I'm sending it back to you to fix a very small bug I found (see my JIRA comment).

Please send to Brian directly once it's fixed.

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/pei-jung/liferay-portal/pull/131. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
