### PR TITLE
LPS-58995 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Hey Marcellus, Leonardo,

Good job on coming up with this solution. I'd like to talk about it with you guys a bit further to see if we can improve it further. In particular, I wonder if we should do this automatically from the Forms admin app instead of making the site admin create the page manually.

I'm also going to add some comments to specific parts of the code for your consideration.

Thanks!
Jorge

**Comment by JorgeFerrer** [comment]
Closing based on the email exchange.

**Pull request closed without merging**
