### PR TITLE
LPS-62561 My Account permissions are not applicable

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
rebase and retest

**Comment by arbetts** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
I need to think through whether we should really remove that section or whether it should be fixed.

In any case, note that if we end up removing it, we should probably do it elsewhere and not just with an if clause in the view. If clauses add complexity to the code and if they are really needed they should be encapsulated where they make sense semantically (that's almost never the presentation layer unless it's really a presentation clause which is not the case here).

**Comment by JorgeFerrer** [comment]
Please see my comment at https://issues.liferay.com/browse/LPS-62561?focusedCommentId=739745&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-739745

**Pull request closed without merging**
