### PR TITLE
LPS-66857 Birthday can be set to a date in the future

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66857](https://issues.liferay.com/browse/LPS-66857).<br><br>/cc @pei-jung @arbetts

### CODE REVIEW

**Comment by drewbrokke** [comment]
I'm going to close we should add a test.

@daledotshan @sherlyliu @arbetts will one of you please write a test for this?  It'll probably need to be a new class (ContactsLocalServiceTest).

**Comment by arbetts** [comment]
i'll add the test

**Comment by sherlyliu** [comment]
@arbetts Thank you for helping to add test case.

**Comment by arbetts** [comment]
https://github.com/drewbrokke/liferay-portal/pull/219

**Comment by sherlyliu** [comment]
I updated junit test.
https://github.com/drewbrokke/liferay-portal/pull/221

**Pull request closed without merging**
