### PR TITLE
LPS-54514

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-54514](https://issues.liferay.com/browse/LPS-54514).<br><br>

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Thanks Drew.

The test failure was caused by format-source. Remember to always run it locally before sending a pull

**Comment by JorgeFerrer** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25116. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Ah right, thank you for the reminder.

--
Drew Brokke

Jr. Software Engineer, Liferay, Inc.

**Pull request closed without merging**
